### ISSUE TITLE
Inconsistent standard name and variable title for two variables

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#114]
The following variables both have the title "Surface Mole Concentration of Dimethyl Sulphide in sea water", which is inconsistent with their standard names:

Omon/co3satcalcos
Omon/co3sataragos

**Comment by martinjuckes** [comment]
Checking with Paul Durack ..

**Comment by durack1** [comment]
@martinjuckes @matthew-mizielinski @jkettleb thanks for pointing out this inconsistency, we are still awaiting for the final CF standard names to be issued for these variables (see http://cfeditor.ceda.ac.uk/proposals/1?status=all&commentfilter=OMIP) so I was awaiting the finalization in CF and once this is complete I will propagate back into the master google sheet (https://goo.gl/Fyr6QW; CMIP6_OMIP_biogeochemistry_standard_output)

**Comment by martinjuckes** [comment]
@durack1 Can you put the proposed standard names in the sheet, so we don't have incorrect names there?

**Comment by durack1** [comment]
@matthew-mizielinski @martinjuckes the correction has been made in the master sheet.

@martinjuckes as there are 150 names under consideration, I have avoided updating all standard_names across the biogeochemistry, chemistry and physics sheets until all are confirmed and accepted. I want to ensure that this is all done once, correctly, rather than getting confused about the uncertain status of some names

**Comment by martinjuckes** [comment]
Now fixed.
