### ISSUE TITLE
Use of missing_value where there is no data

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#116]
Hello Paul ( @durack1 ),

there is a comment at the start of the OMIP sheets that "0." should be used as a data value where there is no actual data: we have discussed this general issue on the WIP and agreed that we should, across all CMIP6, use the missing_value when there is no data ... can you change the comment to reflect this? 

It clearly caused confusion in CMIP5 to have different approaches for different variables.

**Comment by durack1** [comment]
@martinjuckes these values have now been changed to read:
```
3/ As for CMIP5, unless otherwise specified, the ocean diagnostics represent a mean over only the liquid sea water portion of each grid cell (i.e., it is interpreted as "where ocean over ocean"), and the CMIP6 missing_value should be reported where the liquid sea fraction is 0.
```
biogeochemistry: https://goo.gl/Fyr6QW
chemistry: https://goo.gl/BrXVgb
physics: https://goo.gl/Rhrcwp

**Comment by martinjuckes** [comment]
Thanks

**Comment by martinjuckes** [comment]
@durack1 Paul ... why has the layout of the tables changed? Please try to avoid format changes, I'm not running an artifical intelligence project here.

**Comment by martinjuckes** [comment]
@durack1 -- sorry .. looks like it was my mistake.

**Comment by durack1** [comment]
@martinjuckes no problem, no changes on my end other than the minor typo tweaks and CMOR dimensions tweaks in the email thread with Jonathan (Gregory). We are nearing getting the standard names finalized, so I am hoping on a significant update to the sheets when these are available. At that point I will remove the duplicated columns in the sheets, the editing notes provided by Alison (Pamment; the columns, often in blue that include "AP"). I'll make sure to give you a very clear heads up about these changes ***before*** they are made.

I strongly recommend that no more layout/format/type changes are made to the xml files that you're generating as part of the data request. I know that each time @dnadeau4 is trying to convert the data request into the [CMOR json tables](https://github.com/PCMDI/cmip6-cmor-tables/) there are countless new format changes that are causing grief, and additional work for him. We're (@taylor13) also aware that folks are starting to use the [CMIP6_CVs](https://github.com/WCRP-CMIP/CMIP6_CVs) in an operational way, and so are also attempting to minimize any format (or content) changes as is practical..

Also, can you take a peek at [my question to you in the CMIP6_CVs repo](https://github.com/WCRP-CMIP/CMIP6_CVs/issues/166#issuecomment-288488006), I'm trying to use your dreqPy package, but would like some guidance about how best to utilize the latest version of this

**Comment by martinjuckes** [comment]
@dnadeau4 @durack1 Could you clariy what these format changes are that you are causing problems?

**Comment by durack1** [comment]
@dnadeau4 can you please describe the problems to @martinjuckes, or better still point to any open issues you have generated regarding format changes

**Comment by dnadeau4** [comment]
1. `scatratio` `BoundsValues` have `,` separators instead of `space`.  I changed my program so it does not fail anymore.  

2. The other one was the introduction of `comment:`  inside a value (cell_measure or cell_method).  That made my parser do crazy thing.  It is CF-1 compliant, so I had to fix it.  

3. Now I see that we have `area: time: <something>`   My parser expect a value after the `:` character.   I cannot use a regular expression since the order can be `time: <something> area:`.    I will have to create a new function just for this line.  

I don't think @martinjuckes has much say on these except the first one...

**Comment by taylor13** [comment]
yes, I think you're right.  2 & 3 are valid constructs (and used in CMIP6), so as you say, CMOR will need to be able to handle them.

Actually, I'm not sure why you bother to parse these.  Why doesn't CMOR just copy the string you get from Martin into cell_methods?  [I'm sure I must be missing something here.]

**Comment by dnadeau4** [comment]
@taylor13  we have a new `external_variables` metadata and I need to get the `area: areacello`

**Comment by taylor13** [comment]
Yes, you need to parse cell_methods to obtain the external_variables, but the constructs that include "comment" and "area: time ..." are cell_measures.  I don't think you need to parse cell_measures.  Right???

**Comment by dnadeau4** [comment]
That's right.

**Comment by martinjuckes** [comment]
@dnadeau4 `area: time: ....` is also a valid CF. There is a discussion here: https://cf-trac.llnl.gov/trac/ticket/152 and https://www.earthsystemcog.org/projects/wip/time_averages . I've introduced it to be more precise about specifications of weighted time averages. The comment string is added to give a clue about the location of the variable which defines the mask for averaging, when a mask is specified: but you should not need to parse the comment string. Sorry for not flagging this up .. I didn't realise that you were parsing these strings.

 The `area: areacello` strings to be parsed for `external_variables` should only come from `cell_measures` (see section 2.6.3 of http://cfconventions.org/cf-conventions/cf-conventions.html ) -- you should not put anything from `cell_methods` into `external_variables' .

**Comment by dnadeau4** [comment]
We call a `global attribute`  `comment:` and I look for it in the `Table Template` and replace the default value `<comment>` with the values found in Martin's XML.    But, my `replace` function found `comment` in the cell_measures and broke the rest of the line, breaking the entire JSON string as well.   That one was hard to find, but I fixed it, since the JSON string is very long.  

I tried to install `jsonlint` on my machine, but don't know enough about `javascript`, `node` and `browser` to make it work.

You are right, I don't have to handle cell_measure.  It is just a `cut/paste` from Martin XML file.

**Comment by taylor13** [comment]
I may be misunderstanding the above but .... I don't think the global attribute named "comment" which can be provided by the user should be replaced, even if it differs from Martin's.  CMIP6 places no restriction on this attribute.  If a user doesn't supply text for this attribute, then I think CMOR should assign it text from Martin's tables, but otherwise just leave what the user supplies.

**Comment by dnadeau4** [comment]
@martinjuckes @taylor13 

I just noticed that this `modis` variable is back in CMIP6.  It used to be in an extraneous table not used by CMIP6.

CMOR doesn't know how to handle 2 `other dimensions` (**effectRadLi|tau**).  This will fail.

Usually a grid is (Z,Y,X) and time(T) plus 1 singleton(i.e HEIGHT2M)...

Before I do anything, is this a valid CMIP6 variable from `CMIP6_Eday.json`???

=====  
```json
      "jpdftaureicemodis": {
            "modeling_realm": "atmos", 
            "standard_name": "cloud_area_fraction_in_atmosphere_layer", 
            "units": "%", 
            "cell_methods": "time: mean", 
            "cell_measures": "area: areacella", 
            "long_name": "MODIS Optical Thickness-Particle Size joint  distribution, ice", 
            "comment": "",  
            "dimensions": "longitude latitude plev7c effectRadLi|tau time", 
            "out_name": "jpdftaureicemodis", 
            "type": "",  
            "positive": "",  
            "valid_min": "",  
            "valid_max": "",  
            "ok_min_mean_abs": "",  
            "ok_max_mean_abs": ""
        },
```

**Comment by taylor13** [comment]
@martinjuckes   Martin, could you double check that this variable is really wanted by CFMIP?  It seems that the other dimensions = effectRadLi | tau  causes us some problems.
