### ISSUE TITLE
ocean variables in wrong tables

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#119]
@martinjuckes @durack1  

omldamax is in "day" but should be in "Oday".
mlotst is in Eday but should be in "Oday"

hfds in Eday requested by LS3MIP looks wrong to me because it is defined as surface downward 
heat flux in sea water, but LS3MIP shouldn't care about this.  I'm guessing they wanted the net heat flux into the land surface.   If it is retained as is, it should be moved to "Oday".

zfull in Eyr requested by LUMIP and C4MIP is probably not right.  It might be the soil levels for LUMIP.  not sure for C4MIP, but I don't think "height_above_reference_ellipsoid" would be used for the ocean levels.  rather, "depth_below_geoid" is more likely.

rsdoabsorb, tnkebto, and dispkexyfo should be moved from "Eyr" to "Oyr" and check that they don't duplicate variables requested by the omon folks.

The "ocean" and "ocnBgchem"  variables in Emon (there are many dozens of these) should be moved to Omon and check for duplicates.  Also, in Emon a number of variables are labeled "atmos" and have areacella attached, but they should be "ocean" or "ocnBgchem" and have areacello and volcello attached.

**Comment by durack1** [comment]
@martinjuckes I can move these into the appropriate sheets to clean this up. Let me know if this is what you'd prefer, and where to source the (correct) entries from.

For your info the 3 OMIP/Ocean variable sheets can be perused at:
Biogeochemistry: https://goo.gl/Fyr6QW
Chemistry: https://goo.gl/BrXVgb
Physics: https://goo.gl/Rhrcwp

I'm taking a guess at the variables @taylor13 is talking about, I've pulled the info below from http://clipc-services.ceda.ac.uk/dreq/index/CMORvar.html

`zfull (Altitude of Model Full-Levels)` exists in `CF3hr`, `Eyr`, 
`zfullo (Depth Below Geoid of Ocean Layer)` exists in `Oclim`, `Omon` and `Emon` (I suggest the `Emon` entry is removed/deleted)

Candidates for the `physics` sheet: 
`omldamax (Daily Maximum Ocean Mixed Layer Thickness Defined by Mixing Scheme)`, `mlotst (Ocean Mixed Layer Thickness Defined by Sigma T)`, `hfds (Downward Heat Flux at Sea Water Surface)` exists in `Eday`, `Odec` and `Omon` - there are variants `hfdsn` in `LImon` and `hfdsnb` and `hfdsnt` all in `Eday`

`rsdoabsorb (net rate of absorption of shortwave energy in ocean layer)` exists in `Oyr`, `Eyr` and `Emon`

`tnkebto (tendency of ocean eddy kinetic energy content due to parameterized eddy advection)` exists in `Oyr`

`tnkebto (Tendency of Ocean Eddy Kinetic Energy Content due to Bolus Transport)` exists in `Oclim` and `Eyr`, variants `tnkebto2d (Tendency of Ocean Eddy Kinetic Energy Content due to Bolus Transport` exist in `Oclim`

`dispkexyfo (ocean kinetic energy dissipation per unit area due to xy friction)` exists in `Oyr`, `Eyr (with different capitalization)` and `Oclim (also with different capitalization)`, and variant `dispkexyfo2d` exists in `Oclim` (there is also the `v` variant)


Candidates for the `biogeochemistry` sheet: 
Everything @taylor13 indicated in the bottom comment above, referencing the `Emon` variables

**Comment by taylor13** [comment]
one further note about "zfull" and "zfullo".  Sometimes the CMOR name is zfull and sometimes it is zfullo.  Sometimes the variable name is zfull and sometimes it is zfullo.  All combinations can be found across tables Emon, Eyr, Omon, and Oclim.  In CMIP5 we invariably used zfull for both the atmosphere and ocean.  If you want them to be different (o.k. with me), I would invariably use "zfull" for atmosphere (consistent with CMIP5) and "zfullo" for the ocean (for both cmor and variable name).

**Comment by martinjuckes** [comment]
omldamax: fixed
mlotst: this is not in Oday because OMIP have not requested it.

hfdsl added

tnkebto, dispkexyfo: checking with Jonathon, who requested these as 2d variables.

rsdoabsorb: done

zfull: in progress.

**Comment by martinjuckes** [comment]
tnkebto, dispkexyfo adjusted to surface fields in OMIP tables -- FAFMIP and OMIP now using same defns.

**Comment by martinjuckes** [comment]
Resolved in 01.00.07
