### ISSUE TITLE
inconsistent units

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#129]
area fractions in CMIP5 were invariably expressed as percentages (units = "%").  In CMIP6 some are expressed as decimal fractions and others as %.   I think we should make CMIP6 consistent with CMIP5 and make it easier on data users and data providers by making the units fir area fractions invariably "%".  I also find other problems with a "fraction" data.  A look at the data request uncovers the following issues: 
 
3hr: clt  cloud_area_fraction (change units to "%")  Note that all cloud area fractions other than clt and cltc have correct units, consistent with CMIP5.

AERmon: cltc convective_cloud_area_fraction (change units to "%") 

AERmon: siconc sea_ice_area_fraction   (change units to "%";  ALSO THIS SHOULD BE MOVED TO THE SImon TABLE; this is a critical sea-ice variable and should not be "hidden" in AERmon; in CMIP5 it was the first entry in the OImon table, which has been renamed for CMIP6 SImon)

Amon: clt cloud_area_fraction (change units to "%")

CFsubhr: clt cloud_area_fraction (change units to "%")

Eday:  cnc vegetation_area_fraction  (NO UNITS ARE CURRENTLY SPECIFIED; SET TO "%"); also "vegetation_area_fraction" is the standard name for *all* vegetation types so is incorrect.  Unless there is a specific standard name for "canopy", specify "area_fraction" and include a  singleton dimension  to indicate the vegetation type. 

Emon: vegFrac total_vegetated_fraction  This standard name is incorrect.  Should correct to read "vegetation_area_fraction".

Emon: burntFractionAll  This variable should be eliminated because the almost equivalent variable appears in Lmon as BurntArea.  Also the standard name is wrong.  Note burntFractionAll * land fraction = BurntArea.  Could change BurntArea to "mean where land", but that would be inconsistent with CMIP5.  In any case the units should be "%".

Emon: pastureFracC3  (change units to %)  standard name incorrect.

Emon: pastureFracC4  (change units to %)  standard name incorrect.

Emon: nwdFracLut (check whether to change units to %; should be consistent with fracOutLut, fracInLut, and FracLut; see below)  

Eyr: vegFrac total_vegetated_fraction  This standard name is incorrect.  Should correct to read "vegetation_area_fraction".

Eyr:  check whether to change units of fracOutLut, fracInLut, and FracLut

SIday: siconc sea_ice_area_fraction (change units to %)

Simon: sisnconc surface_snow_area_fraction (change units to %)

Simon: siitdconc sea_ice_area_fraction_over_categories (change units to %)

Simon: siitdsnconc snow_area_fraction_over_categories  (change units to %)

Simon: simpconc area_fraction (change units to %)

Simon:  sirdgconc  fraction_of_ridged_sea_ice (change units to %)  incorrect standard name?

day: clt cloud_area_fraction  (change units to %)

fx: sftlf land_area_fraction (change units to %)  note that sea_area_fraction and land_ice_fraction in the same table have correct % units.  Also all the area_fractions in Efx are correct.

**Comment by matthew-mizielinski** [comment]
While this could help a few scientists who simply want to difference and plot these fields, for anyone doing more serious analysis I would expect this to be inconvenient (introducing many divide by 100 operations).

This would also conflict with the CF standard where variables such as sea_ice_area_fraction have Canonical units "1" (see http://cfconventions.org/Data/cf-standard-names/41/build/cf-standard-name-table.html), and I would instinctively interpret any variable described as a "fraction" as being in the range [0,1] rather than [0%, 100%].  We could change all the standard name corresponding to fractions to percent, but this seems like a needless amount of disruption, and additional work, at this stage.

Finally, I note that Martin has also put a significant amount of effort over the last few months into moving from percentages to fractions in the units and variable names. If we _need_ to choose between percentages and fractions for these fields I suggest that fractions would need less support.

**Comment by taylor13** [comment]
It's not that % is intrinsically better than a decimal fraction, but it is used for most of the area fraction fields requested for CMIP.  Most folks don't have software that can automatically interpret units, so it is much easier for them to remember the units if they are consistent.  

I don't know what motivated Martin to start changing *some* of the area fraction units from %, which was invariably used in CMIP5 to fractions for CMIP6, but I think that is a mistake.  If there are compelling reasons to change the units, then we should do it for all area fraction fields.

But one of the values of CMIP is that there is continuity from one phase to the next, so analysis programs don't need to be rewritten.  That's why we should try to keep continuity in variable names and units.

There is no preference in CF for using the canonical units, and a fraction expressed as a percentage is common practice.  The standard name doesn't depend on the units, so there is no need for a change.

**Comment by martinjuckes** [comment]
Hello Both,

On the issue of units and standard names, raised by Matthew: we can't have a standard name for "area percentage", because, as far as CF is concerned, area percentage is just "area_fraction" with units set to percentage (this is just repeating Karl's last line in other words). What I have tried to do is make the long name of the variables consistent with the units. 

I broadly agree with Karl that it would be good to have a common approach, and by default it should be as done for CMIP5. I'll send out an email to the relevant MIPs to see if they have objections.

Time fractions and mass fractions in CMIP5 has units of "1" .. but I don't think that this is worth worrying about at this stage.

**Comment by martinjuckes** [comment]
Opted for % for all area fractions, and "s-1" for their tendencies.
