### ISSUE TITLE
v01.00.04 variables affected to aerosol realm that should go in land realm

### ISSUE THREAD

**Issue by SebastienDenvil** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#139]
Dear Martin,

IPSL's internal review of the data request identified that the following CMOR variable is affected the wrong realm. It have the aerosol realm and we think they should go in the land realm. Let us know if you have any questions or if you need more details.

regards

cpnz

**Comment by taylor13** [comment]
@SebastienDenvil I think you mean "cnpz" (not "cpnz") and I agree.  Note also that canopy height (in several variations) is requested in Emon.  I'm not sure folks will know what to save in "cpnz" given all the variations listed in Emon.  If "cnpz" is different from the canopy_heights requested in Emon, then we should move it to Emon and explain what it is.   Otherwise we should remove it from the Aermon table and ask them to select one of the variables from the Emon table if they want canopy_height.  Also, we should make sure that this is really a function of time in models.

**Comment by martinjuckes** [comment]
I'll replace "cnpz" with "vegheight", which is used by C4MIP and PMIP (and has the correct realm).
I'll check with C4MIP, PMIP, AerChemMIP about the time evolutio.

**Comment by martinjuckes** [comment]
Agreed that vegheight should have a fixed option .. to be added in 01.00.07
