### ISSUE TITLE
The SImon variables that used to have cell_measures=areacello now have cell_measures=areacella

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#158]
There are a number of SImon variables that used to have `cell_measures` equal to `areacello` but that now have `cell_measures` equal to `areacella`, see the dimensions and related information for `str-b220` (http://clipc-services.ceda.ac.uk/dreq/u/f94dae78-80ba-11e6-ab6e-5404a60d96b5.html).

**Comment by durack1** [comment]
@ehogan I have also noticed this issue, thanks for posting

@dnadeau4 @taylor13

**Comment by martinjuckes** [comment]
corrected

**Comment by taylor13** [comment]
Was this correction done consistent with the summary at https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/252#issuecomment-390736977 ?  If so, that issue can probably be closed.  If not, that issue needs to be addressed.

**Comment by matthew-mizielinski** [comment]
@ehogan has prompted me to check whether this got fixed in the recent beta version 01.00.28b1 of the data request and from what I can see it has **not**. For clarity the variables I can see that the following variables in SImon have cell_measures set to areacella, but are not on @taylor13 's list in #252 ;

'sidconcdyn', 'sidconcth', 'sidmassdyn', 'sidmassevapsubl', 'sidmassgrowthbot',
 'sidmassgrowthwat', 'sidmasslat', 'sidmassmeltbot', 'sidmassmelttop', 'sidmasssi',
 'sidmassth', 'sihc', 'siitdconc', 'siitdsnconc', 'siitdsnthick', 'siitdthick',
 'simass', 'simpconc', 'sisaltmass', 'sisnthick', 'sitimefrac',
 'sivol', 'sndmassdyn', 'sndmassmelt', 'sndmasssi', 'sndmasssnf',
 'sndmasssubl', 'sndmasswindrif'

For the SIday MIP table the variables 'sisnthick' and 'sitimefrac' also have cell measures of areacella rather than areacello.

Can we re-open this issue and fix this before the release of 01.00.28? I expect to use this next version for the production of all the UKESM DECK+hist simulations.

**Comment by taylor13** [comment]
@martinjuckes Could you please indicate whether release 01.00.28 has addressed this issue.

**Comment by martinjuckes** [comment]
This is now resolved .. in 01.00.32 or earlier.
