### ISSUE TITLE
Clarify Emon lts

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#165]
Could you help me understand Emon lts? I think it is the difference in potential temperature between 1000 and 750 hPa.  What would you expect to be reported if the surface pressure is lower than 1000 hPa?  I think missing data?  If that's the case is it worth clarifying with a note?

**Comment by martinjuckes** [comment]
@jypeter Jean-Yves: could you comment on Jamie's question above about the Lower Tropospheric Stability requested by PMIP? This variable was used by CCMI, but no other group is requesting it for CMIP6.

**Comment by jypeter** [comment]
I have forwarded the question to Masa Kageyama (who does not have a github account)

**Comment by jypeter** [comment]
I have talked about it with Masa and she says that **we can drop this variable from the PMIP request** (so we can drop it entirely from the DR, if PMIP is the only group requesting it) because:
- we can compute this variable from **ta** (available 19 pressure levels)
- the variable seemed useful when we initially made our request based on variables we knew from PMIP and other projects, but AERchemmip probably had good reasons not to request it even if it was in the old CCMI list

Note: Emon also has some variables that we requested because they seemed useful and were in a list supplied by C4MIP (when we were working on the DR), but PMIP is now the only project requesting these variables! I have not received any answer about that yet (were they dropped by C4MIP on purpose or by mistake) so I'm going to ask Chris Jone if there is a _DR contact_ for C4MIP

**Comment by martinjuckes** [comment]
OK -- PMIP is the only MIP requesting it, so I will drop it.
