### ISSUE TITLE
Multiple frequencies in tables Amon, monClim and mon

### ISSUE THREAD

**Issue by durack1** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#166]
@martinjuckes it seems that the DataRequest version `01.00.07` is returning multiple frequencies for the `Amon`, `monClim` and `mon` tables.

The code attached produces the error: `AssertionError: Multiple frequencies in table Amon: monClim, mon`

[queryFreqAndRealm.py.txt](https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/files/948741/queryFreqAndRealm.py.txt)

see WCRP-CMIP/CMIP6_CVs#166

**Comment by durack1** [comment]
@taylor13 pinging you here

**Comment by taylor13** [comment]
@martinjuckes @dnadeau4 
Martin, you've included some frequency=monClim variables (4 instances) in the Amon table.  Was this by design?   I think all other CMIP6 tables contain variables all sampled at the same frequency.   I know we've discussed this many times before, but I just learned that CMOR assumes that all the variables in a single table have the same frequency.  Here are some options:

1) place the 4 variables in a new "AmonClim" table.  (not too difficult?)
2) eliminate all the frequencies that have "clim" in them.   (i.e., change monClim to mon, and 3hrClim to 3hr, yrClim to yr, etc., but we should check that no one relies on the more specific designation of frequency)  (not too difficult)
3) Modify CMOR to extract frequency on a per-variable basis (difficult).

what do you think?

**Comment by taylor13** [comment]
@martinjuckes @dnadeau4
I just noticed https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/147#issuecomment-291803000 where you indicate you don't want to do 2.  What about option 1 above?

If option 3 is best, then where can the frequency be obtained on a per-variable basis from DREQ?

**Comment by martinjuckes** [comment]
The frequency is in the "frequency" attribute of each "CMORvar" record in the data request.
