### ISSUE TITLE
Update all OMIP/ocean variable lists with new standard_names

### ISSUE THREAD

**Issue by durack1** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#171]
A very large number of CF standard_names were requested for new ocean biogeochemistry, chemistry and physics variables back in September 2016 ([with 124 currently listed on the CFEditor page](http://cfeditor.ceda.ac.uk/proposals/1?status=inactive&namefilter=&proposerfilter=Durack)). Many of these requests have now been completed, and the revised names need to be updated in the 3 source google sheets that define these variables

Biogeochemistry: https://goo.gl/Fyr6QW
Chemistry: https://goo.gl/BrXVgb
Physics: https://goo.gl/Rhrcwp

When this update occurs, many of the working informational columns in each of these sheets will also be removed.

As the data request is reading these files in order to ingest the variable definitions, this issue acts as a placeholder for @martinjuckes so when the update occurs to these external files, this issue will be updated. Once the information in the revised sheets is pulled into the data request, the issue can be closed.

@taylor13 @johndunne13 @jonathangregory @StephenGriffies @japamment

**Comment by martinjuckes** [comment]
@durack1 Please don't remove columns from the sheets until after I have taken a copy -- you can always make a new clean copy for your own use. @japamment : do you have an estimate for when these will be in the standard name table?

**Comment by durack1** [comment]
@martinjuckes no problem, before making any changes I will give you a heads up by commenting on this issue first.. If all goes well I hope to start that next week.

I'm dropping down a link that provides the information that will need to be transcribed across into the google sheets:
[OMIP accepted standard_names](http://cfeditor.ceda.ac.uk/proposals/1?status=complete&namefilter=&proposerfilter=&descfilter=&unitfilter=&yearfilter=&commentfilter=OMIP&filter+and+display=Filter)
[OMIP rejected standard_names](http://cfeditor.ceda.ac.uk/proposals/1?status=rejected&namefilter=&proposerfilter=&descfilter=&unitfilter=&yearfilter=&commentfilter=OMIP&filter+and+display=Filter)

**Comment by martinjuckes** [comment]
@durack1 When do you expect to finish updating the sheets?

**Comment by durack1** [comment]
@martinjuckes I have managed to ascertain the mappings for all but two of the remaining biogeochemical names.. I hope to get these finalized soon, update all the sheets with the new names and then give you an opportunity to make copies before doing the final cleanup (deleting the "working" columns that were used during the standard_name discussions). I have made amendments to the names in the chemical sheet earlier today

**Comment by durack1** [comment]
@martinjuckes I have now also updated the biogeochemistry standard_names (https://goo.gl/Fyr6QW). There are a couple of items to clarify, as one inconsistency has arisen. `surface_downward_mass_flux_of_carbon_dioxide` was rejected in the CF request, however this is now inconsistent with the other `carbon_dioxide` flux variables which are all `mass` values, whereas the existing `surface_downward_mole_flux_of_carbon_dioxide` has different units.

You should have also noted some queries raised on the CF mailing list for the physics standard_names (https://goo.gl/Rhrcwp; http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2017/059479.html). A number of these names are yet to be approved and accepted.

I have not purged any of the "working" columns, however will do that in the near future - my items remaining to complete are now included in the front "general" sheet with "TODO" in the row text

**Comment by durack1** [comment]
@martinjuckes the chemistry sheet (https://goo.gl/BrXVgb) is now finalised. The standard_names have all been updated and the priorities have also been adjusted following the discussion in #150. @johndunne13 and I amended these entries following the logic that the annual 3D fields are most important. Is there still a naming conflict? And in addition are you happy for me to delete the redundant/working columns?

For the biogeochemistry there are still some standard_names and units to be finalised, and there are some other notes in the first sheet of the file that also require finalising. Regarding the naming conflicts and the data volume/priority of 3D fields, I will reply over at #150

**Comment by taylor13** [comment]
@durack1 @martinjuckes For the "discussion" columns that are not being used (redundant) and are in some cases at least wrong, why not delete their contents but not the column itself.

**Comment by martinjuckes** [comment]
Hello @durack1 , @taylor13 , @johndunne13, @jamesorr , I've been going through the OMIP variables. There are still 24 variables which are listed in the biogeochemistry google doc (https://goo.gl/Fyr6QW ) as being requested as (1) yearly 3-d, (2) monthly near surface and (3) monthly 3-d. These are `arag, bacc, calc, co3, co3abio, co3nat, co3satarag, co3satcalc, detoc, dissic, dissoc, nh4, ph, phycalc, phydiat, phydiaz, phymisc, phypico, po4, talk, zmeso, zmicro, zmisc, zooc` and `...os` variants for the near surface variables. In some cases the monthly 3-d fields and the near surface fields are requested at the same priority. There is some redundancy here and Karl has recommended (in #150 ) that we take out the redundancy and either omit the monthly 3-d field, or omit the annual and monthly near surface field. Is there a preference from OMIP?

**Comment by durack1** [comment]
@jgjgfdl @johndunne13 @jamesorr just pinging all again here, so you can get @martinjuckes a reply and get this issue resolved

**Comment by johndunne13** [comment]
It is up to Jim, but I suppose if there is aversion to having both monthly
and annual 3D variables as priority 1, we could make the monthly 3D
variables priority 2.

**Comment by martinjuckes** [comment]
Hello @johndunne13 , @jamesorr, We could take that approach. @taylor13 raised a mild objection when I suggested it last year in the discussion thread #150 ... Karl's preference was to leave out the request for monthly 2d variables if you are requesting the 3d version (see hi comment from 12th April).

**Comment by taylor13** [comment]
On reflection, a case *could* be made for collecting both 3-d fields and the uppermost layer of the 3-d field (i.e., a 2-d field) if the time-slices requested differed.  For example, you might request the 2-d field for all months of a simulation, but the 3-d field only for the first and last year of the simulation.  

Also, I now think it may make sense to suggest that the 2-d field could be requested at a higher priority than the 3-d version of the table because some groups might only be willing to supply 2-d fields.

**Comment by martinjuckes** [comment]
In order to implement Karl's suggestion above, I intend to make the following changes (the variable label in the first column is the stem of the name, the variable name will generally end in "os" for the Omon 2d version of the variable, all the Oyr variables listed here are 3d):

Variable       |     Oyr         | Omon 2d   | Omon 3d
----------       |     -----         | ------------   | -----------
arag |                2 |                2 |                2 --> 3
bacc |                3  --> 2|                3 --> 2 |                3
calc |                2 |                2 |                2 --> 3
co3 |                2 |                2 |                2 --> 3
co3abio |                2 |                2 |                2 --> 3
co3nat |                2 |                2 |                2 --> 3
co3satarag |                2 |                2 |                2 --> 3
co3satcalc |                2 |                2 |                2 --> 3
detoc |                2 |                2 |                2 --> 3
dissic |                1 |                1 |                1 --> 2
dissoc |                2 |                2 |                2 --> 3
nh4 |                2 |                2 |                2 --> 3
ph |                1 |                1 |                1 --> 2
phycalc |                3 --> 2|                3 --> 2|                3
phydiat |                3 --> 2|                3 --> 2|                3
phydiaz |                3 --> 2|                3 --> 2|                3
phymisc |                3 --> 2|                3 --> 2|                3
phypico |                3 --> 2|                3 --> 2|                3
po4 |                1 |                1 |                1 --> 2
talk |                1 |                1 |                1 --> 2
zmeso |                3 --> 2|                3 --> 2|                3
zmicro |                3 --> 2|                3 --> 2|                3
zmisc |                3 --> 2|                3 --> 2|                3
zooc |                2 |                2 |                2 --> 3

I have decreased the priority of Omon 3d variables, except where it is already at 3, in which case I have increased the Omon 2d and Oyr 3d priorities to 2.

**Comment by durack1** [comment]
@jasminjohn pinging you here

**Comment by jgjgfdl** [comment]
John replied to email thread that these changes look good.
Thanks!

**Comment by durack1** [comment]
@jgjgfdl I assume you're Jasmin, thanks for clarifying..

**Comment by jamesorr** [comment]
@martinjuckes, @jgjgfdl, @durack1 , @taylor13 , @johndunne13:
Martin's changes to the priorities based on Karl's suggestion are fine by me. Thanks Jasmin for your efforts to clean up the worksheets.

**Comment by martinjuckes** [comment]
See OMIP_BGC_CHEM_changes_20180531.txt file from JASMIN for long names.

**Comment by martinjuckes** [comment]
All fixed in 01.00.24

**Comment by jgjgfdl** [comment]
Hi,

Sorry to be a pain, but in looking at Data Request 01.00.25, it appears the ocean bgc tracers in Omon may be awry - they are listed as being 2-D instead of 3-D.

As an example, 'dfe' in Omon is listed as 
dfe {Omon}: Dissolved Iron Concentration [mon: Temporal mean, Global field (single level) [XY-na] {:depth0m} [amse-tmn]] 

I believe this should actually be: Global ocean field on model levels **[XY-O]** [tmean]  
(as for the identical Oyr variable).

Is it possible to issue a quick patch update to DR #25?

Many thanks,
Jasmin

**Comment by durack1** [comment]
@jgjgfdl thanks for keeping an eye on this!

**Comment by jgjgfdl** [comment]
Hi Martin,
Thank you very much for all the effort to get an updated Data Request 01.00.26 out  to correct the 3-D Omon fields. 
Unfortunately, I'm sorry to have to report that not all of the fields were changed to [XY-O] as desired.
Below is a list of ocean bgc fields in Omon that need to be updated to 3-D, ie.  **[XY-O]** :
bfe
bsi
chl
chlcalc
chldiat
chldiaz
chlmisc
chlpico
dfe
dissi13c
dissi14cabio
dissicabio
dissicnat
no3
o2
o2sat
phabio
phnat
phyc
phyfe
phyn
phyp  
physi
pon
pop
pp
si
talknat

Thanks in advance for your help to resolve the issue!
Jasmin

**Comment by martinjuckes** [comment]
Dear Jasmin, have you checked the priorities of these variables? These "desired" changes have not been made because the variables haven't been included in the above discussion ... see https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/171#issuecomment-391692449

**Comment by jgjgfdl** [comment]
Hi,

Thanks for the reply. 
My understanding was although the discussion started with the 24 variables mentioned early on, the outcome applied to all the variables (tracers) in the biogeochemistry google doc (https://goo.gl/Fyr6QW ), which has 52 tracers requested as yearly 3-d,  monthly near surface and monthly 3-d with differing priorities.
Although the variable priority may be other than '1', I think the dimensionality of the variable should be updated in the Data Request to avoid any potential confusion - so if a variable is 3-D (x,y,z) it should be noted as such.

Thanks,
Jasmin

**Comment by martinjuckes** [comment]
Have you checked the priorities of these variables?

**Comment by jgjgfdl** [comment]
Hi,

They are priority 2 or 3.
However, the dimensionality as noted on the Data Request is incorrect, and I think it is important to resolve this.
If eg a group decides to provide 'pp', a priority 3 Omon variable, the Data Request states it is [XY], when in fact the variable is (x,y,z).
It's alsoconfusing that the same variable has the correct dimension in Oyr, but different (incorrect) dimensions in Omon (eg dfe and other tracers mentions).

Thanks,
Jasmin
