### ISSUE TITLE
v01.00.08: Minor issue with time dimensions in Efx

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#175]
There are a number of variables in the `Efx` table with a time dimension (see [here](http://clipc-services.ceda.ac.uk/dreq/u/MIPtable::Efx.html)), this includes:
 * `rsd`, `rld`, `rsu`, `rlu` : all have frequency `fx` and dimensions `alevel spectband time`
 * `ps`: has frequency `3hr`, but no `time` dimension
 * `vegHeight`: `time` in dimensions, `area: time: mean` in cell_methods 

I guess that some of the above may have seasonal cycles, but if I haven't missed something (quite possible) the time coordinate should be `time2` rather than `time`.

**Comment by martinjuckes** [comment]
rsd, rld, rsu, rlu amd vegheight fixed in 1.00.09; the ps variable in Efx should have frequency fx: this will be fixed in 01.00.11

**Comment by senesis** [comment]
However, I do not understand what variables rsd, rld, rsu, rlu should represent, in this table ? Some radiative fluxes which are fixed in time and with horizontal location, and are variable with spectral band and model level ?? Is it a kind of climatology of single-column radiative scheme ? If yes, should it really be qualified as 'fixed'
