### ISSUE TITLE
v01.00.08: wsgsmax100m, ua100m, va100m

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#176]
The variables `wsgsmax100m`, `ua100m` and `va100m` have an unset modeling_realm.
For `wsgsmax100m` ("Maximum Wind Speed of Gust at 100m") an incorrect structure id is assigned giving it the coord/dimension `height10m` rather than `height100m`

**Comment by jkettleb** [comment]
Can I just check the table is right too?  Its currently 6hrPLev.

**Comment by martinjuckes** [comment]
The dimensions have been fixed. The table is right, I'm afraid. There were competing calls for keeping the numbers of tables smalls vs. having different tables to keep different types of variables apart. This is were we landed when the discussions were forced to stop. 6hrPlev includes pressure level data and, as in CMIP5, surface fields and (as a slight extension) near surface fields (which, confusingly, are on height rather than pressure levels).
