### ISSUE TITLE
surface albedo issues

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#185]
There should be no reason to collect "albedo" (when it measures reflectivity over all wavelengths and over the entire grid cell), if we also collect the incident and reflective shortwave radiation.  That being said, we should at least be consistent with how we label surface albedo.  Note in current request the differences in 6hrPlevPt (albsrfc), AERmon (albs *and* albsrfc), and Eday (albs).

I think "albs" is slightly better than "albsrfc".  We certainly don't need both.  And I don't think we need the monthly values, since we'll be collecting down and up shortwave at the surface in Amon.

Similarly, we could do without albs in Eday because we're collecting the SW up and down in "day".

Those requesting surface albedo for monthly and day should simply request rsds and rsus instead.

**Comment by martinjuckes** [comment]
There has been some discussion about this: although there is a local relation between albedo and reflected shortwave, you can't convert from one to the other -- certainly not in the monthly mean.  Energy budgets clearly need the fluxes ... I'll check with the MIPs to see what the us of albedo is. I think albs should be the planetary albedo ... but is linked to the wrong standard name.

**Comment by taylor13** [comment]
thanks, Martin.  It is true that you won't be able to get "average albedo" from the fluxes, but I'm pretty sure no one is interested in that.  (The average will also depend on how you treat night time, when albedo is undefined.  For cases where I've seen mean albedo reported, the albedo is weighted by the incident radiation, so that in fact the weighted-mean albedo can be used to obtain the mean upwelling radiation from the incident radiation -- a simple product.)

**Comment by martinjuckes** [comment]
Hello Karl, I though albedo could be defined as a property of the surface which exists even after the lights are turned off -- but I take your main point that common usage in climate modelling is related to the ratio of fluxes. This may be changing as models develop more detailed representations of surface properties. In the email thread I've asked Hyungjun about the canopy albedo requested in LS3MIP -- to see if they have a preference regarding weighting (I'm not sure that it matters very much, but if there is a preference I would like to have it at least declared in the request, so that data providers know what is expected).

**Comment by martinjuckes** [comment]
ISMIP6: might be a case for "plane albedo" (a property of the physical surface) being analysed --- but no specific plans in CMIP6, so we can drop it;

SIMIP: not needed: the fluxes give enough information;

**Comment by taylor13** [comment]
Just one follow-up comment:  I'm not that familiar with recent models, but in earlier models I think at least two surface albedos were usually calculated, based on the composition of the underlying surface: the direct-beam albedo (which might have some angular dependence) and the diffuse radiation albedo.  Given different mixes of surface types within a grid cell and different times of day (sun angles), the model then produces a net direct albedo and net diffuse albedo based on a weighted average of the albedos specified for each of the contributing surface types.   of different mixradiation vs. direct-beam radiation and independent of incident angle of the direct-beam (e.g., the albedo of forested land in the tropics *might* in some models be a constant, then it might be nice to know what that albedo is.  

It probably would be nice to know what basic albedos are for individual surface types, but these would be fixed fields (I think).  Even with these, you couldn't explain model differences without knowing how they were combined and weighted, what the angular dependence was, and how different the ratio of diffuse to direct radiation is in different models.

**Comment by martinjuckes** [comment]
Some models appear to have more complex vegetation albedos now, and I suspect that the age of the ice/snow surface, which is requested, may also play a role: there has been a lot of discussion about the impact of changing albedo ice melt rates.  
RFMIP is asking for a surface albedo as a function of radiation bands  (albdirbnd: http://clipc-services.ceda.ac.uk/dreq/u/590f3f16-9e49-11e5-803c-0d0b866b59f3.html ) .. so they must be expecting some models to resolve spectral dependence of albedo. They are also proposing a new standard name, "surface_direct_albedo", to go with this.  
When you say "each contributing surface type": would you expect a different albedo for each modelled surface type (the types used in the "landCoverFrac" Lmon variable)? We could put in a request for fixed direct and diffuse surface albedo as a function or "vegtype", perhaps with a low priority. There don't appear to be clear plans to analyse this, but that may be because none of theMIPs has looked at the broad picture energy budget.

**Comment by taylor13** [comment]
No, I don't think we should suggest adding additional albedo fields to the data request.  I f someone else request these, we should ask them how they plan to use them in an analysis.  Make sure they've really thought about it.

**Comment by martinjuckes** [comment]
@taylor13 : Hello Karl, I think this is the current status on albedos:

* sialb removed from SIMIP: made redundant by fluxes;
* direct and diffuse band resolved albedos retained in RFMIP;
* aerosol single scattering albedo on model levels retained for RFMIP: specific information about aerosols;
* albisccp (ISCCP cloud albedo) retained for direct comparison with ISCCP;
* monthly surface albedo: removed from request (redundant);
* **albsrfc 6-hourly: retained in HighResMIP** request as not redundant at this frequency (surface fluxes are requested at 3 hourly intervals by CFMIP .... perhaps room for improvement here.)
* albc: daily canopy albedo requested by LS3MIP: complex function of canoy properties .. specific usage.
* **planetary albedo, daily: does not appear to be needed**.
* albsn: daily snow cover albedo requested by LS3MIP: function of snow age .. specific usage.

**Comment by martinjuckes** [comment]
See also https://github.com/PCMDI/cmip6-cmor-tables/issues/75

**Comment by martinjuckes** [comment]
Martin Vancoppenolle has raised an issue  PCMDI/cmip6-cmor-tables#75 asking for sea ice albedo to be re-introduced.

It was dropped as being probably redundant (as you indicate) and probably ambiguous (because there are several possible variants). In particular, what is measured from space might be a direct or diffuse albedo, but the ration of incoming to outgoing radiation is going to depend on the angle of incidence of the radiation. @martinvancop : Can you look through the comments above and suggest a definition for the albedo which you want?

**Comment by dirknotz** [comment]
After some discussion within SIMIP, we would like to ask for the "broadband, category-averaged sea
ice albedo (excluding open water)"

**Comment by martinjuckes** [comment]
Hello Dirk, I'm afraid I don't understand what you mean by "category averaged" ... can you expand on it a little?

**Comment by taylor13** [comment]
The reason given for collecting sea ice albedo is, apparently, "I know at least 3 important climate groups who may not provide [the incident and reflected SW radiation over sea ice] fields (for technical / time reasons)."  Presumably, they will provide at least *one* of these fields (incident SW?) or else they won't be able to analyze the surface energy budget, which presumably is the main reason for needing to know albedo.  If you are asking for anything but an instantaneous value of albedo, and if the sea ice albedo depends on sun angle and/or wavelength and/or the fraction of incident radiation that is direct beam vs. diffuse and/or the fraction of each sea ice "category" , then the albedo reported will in fact have to be evaluated by accumulating the incident and reflected shortwave radiation over time, and then computing their ratio.  Why not just report the mean fluxes (*where sea ice*; not for the entire grid cell) since you've already computed them? If you simply report an unweighted average of the albedo, you won't be able to compute surface energy budgets (even knowing the incident SW radiation). 

If I have missed some good reason for reporting albedo rather than the fluxes *where sea ice*, then please provide detailed instructions on how the albedo should be computed including:
1) how the time-mean should be calculated (including weighting by incident radiation, weighting by sea ice category, weighting by diffuse vs. direct beam, etc.)
2) whether a single albedo should be reported (i.e., the effective albedo over all wavelengths or only over certain "broadbands" of the SW spectrum.
3)  Whether separate albedo values should be reported for direct beam and diffuse SW radiation.

**Comment by dirknotz** [comment]
After some further discussion within SIMIP, we have now decided to stick to the initial decision of not asking for albedo in CMIP6. 

Thanks, Karl and Martin, for your insisting that we are really, really specific about what we want. Trying to formulate our request has brought us to the conclusion that we can't really do so in a meaningful way. The ways in which sea-ice albedo is handled and calculated in individual models, and the ways in which it is measured by some satellites are simply too different to allow for a meaningful reporting of albedo at this point in time. 

We will, however, use this discussion to examine further how albedo should be reported in models to allow, among others, for a meaningful comparison to satellite data. This, however, must happen on such detailed level that it is not meaningful to do so within CMIP6 at this point in time, we believe. The chances of there being misunderstanding and mis-interpretations is simply too large. Hence: no sea-ice albedo to be asked for.

Thanks again!

 Dirk

**Comment by taylor13** [comment]
thanks for your patience and for thinking about this deeply. 
best,
Karl

**Comment by martinvancop** [comment]
We have re-examined the issue. Sea ice albedo is a GCOS variable and several groups would like to have it. We also have a more consistent definition now, compared to 7-8 years ago. Therefore will add sea ice albedo to our groups, within a specific GCOS_seaice variable group, valid for our opportunity.

**Comment by taylor13** [comment]
For evaluation of the energy flows into and out of sea ice (which determine its growth and deterioration), the surface radiative fluxes are needed.  I would think these fluxes would be essential for a number of studies.  If these are saved, then what added value is there in saving surface albedo of sea ice? Recall that we are trying very hard to limit the volume of model output produced by CMIP.   Are you suggesting that rather than request the incident and reflected shortwave radiation, you collect only surface albedo?  I think that would rule out addressing a number of interesting scientific issues.

**Comment by martinvancop** [comment]
Hi Karl, we realise all constraints quite well. In this case we feel that GCOS community requests are important to consider. Their community evaluation (Lavergne et al BAMS 2023) recommends daily albedo output as the most useful option. Currently, we would only save save monthly sea ice energy fluxes in the "seaice_energy_budget" opportunity. Which is why, in the end, we suggest having daily albedo in the GCOS sea ice variable group, without touching the "seaice_energy_budget" monthly variable group.

**Comment by taylor13** [comment]
Hi Martin,
I might be wrong about this, but my understanding is that the variables needed to exploit one opportunity may also be included in other opportunities; that is, the sets of variables associated with each opportunity may overlap.  If so, you're free to include any variables you need.

On a technical note, how is the daily mean albedo calculated (both by the GCOS community and in models)?  I assume it is the ratio of the mean fluxes of incident and reflected radiation.  And I assume it is designated as "missing" during the polar night.  Please correct me if I'm wrong.   
Karl

**Comment by martinvancop** [comment]
Yes you are guessing well can check the definition in SIday.sialb. I don't know about GCOS definition (I don't know if they have one), it is a good idea to ask.
