### ISSUE TITLE
sltbasin vs sltnorth vs sltnortha

### ISSUE THREAD

**Issue by TimGraham1982** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#190]
sltbasin and sltnorth appear to be the same variable based on the descriptions in the data request.

Also sltnortha is the Atlantic ocean salt transport but sltnorth (and sltbasin) has a basin dimension and therefore already includes the Atlantic ocean salt transport. 

Could this be reduced to just requesting sltbasin (the name is then consistent with hfbasin)?

**Comment by martinjuckes** [comment]
sltbasin and sltnorth do look to be the same, I'll merge these. I'm not sure why PMIP is requesting sltnorth and sltnortha -- I'll check with Jean Yves.

**Comment by martinjuckes** [comment]
@jypeter : Jean Yves: the PMIP request, in the PMIP-Omon sheet, includes requests for both sltnorth and sltnortha. sltnorth is defined as being salt transport as a function of latitude, basin and time. sltnortha appears to be the same for the atlantic only, which is redundant as it would be included as part of sltnorth?

**Comment by martinjuckes** [comment]
sltnorth now removed (01.00.12).
sltnortha still there for now ...

**Comment by jypeter** [comment]
@martinjuckes I have just asked Pascale Braconnot. We requested these variables, because we originally found them in the **SPECS_Omon** table, with the following description:
-  **sltnorth**: Northward Ocean   Salt Transport
- **sltnortha**: Atlantic Northward Ocean Salt Transport

Pascale wants to have both variables (total and Atlantic), because it will  be useful for paleo studies. She is not that interested in the other basins

So I guess either we keep **sltnorth** over **all** the basins (btw, where can I find the list of basins on the DR COG site), because we can compute the total over the basins, or we keep _sltnorth_ and _sltnortha_, but then we don't need a _basin_ dimension. I think keeping sltnortha over the basins is a mistake.

Link to the var on the DR web site: [sltnortha](http://clipc-services.ceda.ac.uk/dreq/u/16566aed8c1a15e598240020f11b8fd4.html)

I'm sending the URL of this issue to Pascale so that she can check if I got what she said correctly

**Comment by jypeter** [comment]
Oh, I did not get things correctly! I now understand the question better: _why do we need sltnorth (over the basins), if this information is already provided in the _sltbasin_ variable?_

It's possible we only need sltbasin and that you can remove sltnortha.

Pascale, can you check [sltbasin](http://clipc-services.ceda.ac.uk/dreq/u/59171588-9e49-11e5-803c-0d0b866b59f3.html)?
