### ISSUE TITLE
lwtoacs cmor label inconsistent

### ISSUE THREAD

**Issue by StephanieWoodward** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#191]
Title associated with lwtoacs indicates that it is the clear-sky longwave radiative flux due to dust.  For consistency with other requests, the cmor_label should be lwtoacsdust.

**Comment by martinjuckes** [comment]
@jypeter : Jean Yves: can you comment on the relationship between the variable lwtoacsaer, which was used in CCMI and is requested by PMIP through the PMIP-aero sheet of your request, and the variable lwtoacs which is introduced by PMIP as a new variable and defined as clear-sky radiative flux due to dust?  lwtoacsaer is requested along with lwtoaasdust, swtoacsdust and swtoaasdust, so the naming appears inconsistent.

**Comment by martinjuckes** [comment]
Changed to lwtoacsdust in 01.00.17
