### ISSUE TITLE
Cell method for fracInLut and fracOutLut : is it really 'time:sum' ???

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#202]
see http://clipc-services.ceda.ac.uk/dreq/u/d22e47d6-4a9f-11e6-b84e-ac72891c3257.html
What is the physical meaning of adding fractions ?

**Comment by martinjuckes** [comment]
If 1% is exchanged each month, the annual sum is 12%. It is the sum of the fractional amounts transferred each time step over the course of the year. I suppose it is a habit of the land use modelers that, for this variable, they tend to talk about summed increments rather than a mean compoenent of the tendency.
