### ISSUE TITLE
hus4 and wap4 are requested as 6hr time-averages on pressure levels

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#208]
This request represents a slightly significant processing load for the interpolation to pressure levels. So, I would welcome a confirmation that this request actually is for time-averaged variables, and, if yes, what is the required/expected/recommended time sampling in the 6hr period

**Comment by martinjuckes** [comment]
This is required, but they are not prescribing a specific time sampling. This is the response from Malcolm Roberts:

> When we consulted our community, they explicitly requested time means for these variables, when looking at drivers of extremes (compared to the instantaneous values that we use for tracking particular features). So there is a good reason for having both.
> 
> As regards the frequency of data used in the mean, then I guess that depends on what is possible. I confess that our model does the processing internally so I don't have experience of comparing a mean field from say 3 hourly data, and from using each timestep. But we do output explicitly some variables using 6 hour meaning in order to compare to reanalyses (which do, or used to, do the meaning in that way).
> So maybe that could be a better metric, if you can match typical reanalysis meaning method then the data will then be comparable to our best reference dataset.
> Otherwise it is best efforts.

You are already dealing with monthly and daily means on pressure levels ... presumably your question arises because you believe that the time sampling used for the monthly and daily means (also unspecified) is not appropriate for the 6 hourly means?

I will add a comment suggesting that people add information in the cell_methods string of the form `(interval: 1 hr)`, e.g. `cell_methods="area: time: mean (interval: 1 hr)"`.

**Comment by senesis** [comment]
Thanks. I do not think that there is much data available for long periods of time and for upper layers at high frequency (I mean better than 6hr) ingested in reanalyses, at least before the satellites era; anyway, we will check the cost of high frequency sampling
Regarding the suggestion comment, I am afraid that using comments does not fit the automated processing framework that is implied by the complexity of the DR. But I agree that there is no other solution

**Comment by martinjuckes** [comment]
I've added an issue for consideration in CMIP7: https://github.com/cmip6dr/cmip7_forward_look/issues/9
