### ISSUE TITLE
Exact time of the day for instant CMIP6 variables

### ISSUE THREAD

**Issue by svalcke** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#234]
We did not find any precision on the exact time of the day onto which instant CMIP6 variables have to be produced. For example, for 3hr instant variable, do we have to produce the variable at 0h, 3h, 6h, etc or is it OK to produce them at 1h30, 4h30, 7h30, etc ?

**Comment by martinjuckes** [comment]
I don't think we have specified the instant, but perhaps Karl (@taylor13) can comment.

**Comment by taylor13** [comment]
We may not have done so yet, but we should specify this.   For consistency with CMIP5 and if there is no objection (and no guidance coming from those requesting the output), samples should be reported (with all times astronomically determined and applying at 0 E):

for 6-hourly data:  
point samples:   0, 6, 12, 18   
Many of the 6-hourly samples have been requested as time-means, but I think this is probably a mistake.   This data is generally more useful as instantaneous time-samples, not means.   If after checking with those requesting data, if time-means are actually needed, then for
mean samples: 0-6, 6-12, 12-18, and 18-24.

For 3-hourly data:
point samples:   0, 3, 6, 9, 12, 15, 18, 21
mean samples:   0-3, 3-6, 6-9, 9-12, 12-15, 15-18, 18-21, 21-24

For 1-hourly data:
point samples:    0, 1, 2, 3, ... , 23
mean samples:    0-1, 1-2, 2-3, ..... 23-24.

The frequency of sub-hourly data is tied to the model time-step, so we can't specify time of day.

**Comment by senesis** [comment]
Refering to 

> Many of the 6-hourly samples have been requested as time-means, but I think this is probably a mistake.

Could the check with those requesting the data be undertaken quite quick ?
Also : can each lab decide whether means are computed e.g. as ]0,3] or as [0,3[ ?

**Comment by martinjuckes** [comment]
I have checked the 6-hour means before, but can check again. 
3 of them (prhmax, wsgmax10m and wsgmax100m) are actually 6-hourly maxima which fall in the same frequency category as means. For these we definitely need the "mean sample" category. I've put some text here: https://earthsystemcog.org/projects/wip/time_of_day (and added a comment about other non-point data that uses the same intervals as the means).

**Comment by martinjuckes** [comment]
From Malcolm Roberts (for HighResMIP), I've already had this answer (which is also addressing a question about the frequency of data which should be used to calculate the 6-hourly mean: e.g. does it have to be time-step data, or could it be 3-hourly): 

> Hi Martin (and others who addressed the same question to me),
I had this question from several of you regarding the time means for these variables, and I'll try and answer it.

> When we consulted our community, they explicitly requested time means for these variables, when looking at drivers of extremes (compared to the instantaneous values that we use for tracking particular features). So there is a good reason for having both.

> As regards the frequency of data used in the mean, then I guess that depends on what is possible. I confess that our model does the processing internally so I don't have experience of comparing a mean field from say 3 hourly data, and from using each timestep. But we do output explicitly some variables using 6 hour meaning in order to compare to reanalyses (which do, or used to, do the meaning in that way).

> So maybe that could be a better metric, if you can match typical reanalysis meaning method then the data will then be comparable to our best reference dataset. Otherwise it is best efforts.

> Thanks, Malcolm

**Comment by taylor13** [comment]
@senesis Regarding 3-hour  time-means for ]0,3] vs. [0,3[, I think the time-means should be calculated based on a weighted mean of the samples, so they will be insensitive to the open/closed choice of bounds.  

For example, if the samples are every half hour for times 0:15 , 0:45, 1:15, .... 23:45, then the first 3-hour mean will include the first 6 samples, weighted equally.  

If, on the other hand, a model provides values every half hour at 0:00, 0:30, 1:00, ... 23:30, 24:00, then the first 7 samples will contribute to the mean with the first and last sample weighted  half as much as the others (since those samples span intervals that overlap the previous mean period and the next mean period).

Does this seem o.k. to you?

Malcom's suggestion to do the means the same was as in reanalysis certainly has merit if someone can figure out what they did in reanalysis.   

I think we should make sure that the periods over which 1-hour means are computed can can be combined with equal weights to form each of the following:  3-hour means, 6-hour means, daily means, and monthly means.  That is: 

each 3-hour mean can be directly computed as the mean of three 1-hour means;  
each 6-hour mean can be directly computed as the mean of pairs of 3-hour means;
each 1-day mean can be directly computed as the mean of four 6-hour means; 
each monthly mean can be computed directly from the daily means inside the month.

**Comment by senesis** [comment]
I see at least one issue with this option :

> If, on the other hand, a model provides values every half hour at 0:00, 0:30, 1:00, ... 23:30, 24:00, then the first 7 samples will contribute to the mean with the first and last sample weighted half as much as the others (since those samples span intervals that overlap the previous mean period and the next mean period).
in the case where 'mean' actually applies (as Martin states) to max and min : if the maximum value over two days occurs at 0:00 of the second day, it will impact two daily max values.

So, the rule should be different for max and min, and then the choice of [0,24[ vs. ]0,24] actually matters

**Comment by taylor13** [comment]
good point.  There aren't a lot of these max/min fields, and the choice of which bound is closed must be arbitrary.   It will only affect samples at the bound, so I wouldn't worry about it being consistent across all models.  Just be consistent in how you do it.  Or do you think there is a scientifically good reason to specify the choice?

**Comment by martinjuckes** [comment]
I don't see the problem with the maximum in one range being the same as the maximum in the next range .. if that is what is in the data (as in "The highest point in Oklahoma is also the lowest point in Colorado"). If a time series peaks at midnight, then then we have two maxima which are the same.  If we are asking for a mean from 00Z to 06Z and you chose to compute it from 3 hourly data, then I can't see how anything other than the weighted mean is justified. Averaging values from 03Z and 06Z is just not a fair estimate of the 00Z to 06Z mean. But, on the other hand, the CF Convention does not support any more detailed information, and I've not heard any complaints about lack of detail on this issue in CMIP5, so perhaps we should stick to specifying the time ranges.

**Comment by taylor13** [comment]
So do we agree that we specify the following synoptic (point) sample times and sample intervals (for time-mean data and max/min data)?:
```
for 6-hourly data:
point samples: 0, 6, 12, 18
Many of the 6-hourly samples have been requested as time-means, but I think this is probably a mistake. This data is generally more useful as instantaneous time-samples, not means. If after checking with those requesting data, if time-means are actually needed, then for
mean samples: 0-6, 6-12, 12-18, and 18-24.

For 3-hourly data:
point samples: 0, 3, 6, 9, 12, 15, 18, 21
mean samples: 0-3, 3-6, 6-9, 9-12, 12-15, 15-18, 18-21, 21-24

For 1-hourly data:
point samples: 0, 1, 2, 3, ... , 23
mean samples: 0-1, 1-2, 2-3, ..... 23-24.

The frequency of sub-hourly data is tied to the model time-step, so we can't specify time of day.
```
I didn't follow what Martin said in the most resent comment about max & min sample values being the same.  Clearly the maximum at one location can have the same value as the minimum (or maximum) at another, but I don't think we should consider a time-sample that appears on the bound between two time-intervals as falling within *both* time-intervals.  I would leave it up to each group to decide which interval a boundary sample should be included in (either the interval ending at the bound or the interval beginning at the bound, but not both).  

Note that if we define the intervals as specified above, then 
```
each 3-hour mean can be directly computed as the mean of three 1-hour means;
each 6-hour mean can be directly computed as the mean of pairs of 3-hour means;
each 1-day mean can be directly computed as the mean of four 6-hour means;
each monthly mean can be computed directly from the daily means inside the month.
```
In computing these, there will be no need to weight since the bounds of lower frequency data coincide with a subset of the bounds of higher frequency data.  If this were not the case, then weighting would be required.

**Comment by martinjuckes** [comment]
Exact times of day recorded here: https://www.earthsystemcog.org/projects/wip/time_of_day.
