### ISSUE TITLE
When should ps be submitted?

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#235]
Some ps requests do not appear to have an associated requesting MIP (Esubhr etc).  The provenance information implies they have been added as part of constructing the data request.  Is there any accompanying documentation on when we should provide these variables?

**Comment by martinjuckes** [comment]
Only submit them if they are requested. If they are not requested, they are there so that CMOR can use them, which implies that `ps` will be included in data files of other variables if your configuration is such the CMOR feels the need to put `ps` in the files (i.e. if it is a critical part of the vertical coordinate information).

**Comment by jkettleb** [comment]
Thanks Martin - I think this means as we have a hybrid height based vertical coordinate we do not need to submit these variables.
