### ISSUE TITLE
drop the  'positive' from rsdoabsorb ?

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#263]
Although rdsoabsorb has unins Wm-2 we don't think its a flux so doesn't have direction.

Do you agree or have we misunderstood?

**Comment by martinjuckes** [comment]
I think this *is* a flux of energy into an ocean layer. After discussion with Karl, we have adopted the convention that transfers into the ocean from land or atmosphere should be considered as having a vertical direction and hence requiring a positive attribute.

Looking at this now, I'm not sure that `rdso` is the correct naming stem for this variable ... as it is not really linked with downwelling radiation directly, .. but I think we have to live with that for now (I've raised an issue for CMIP7 here: https://github.com/cmip6dr/cmip7_forward_look/issues/14 )

**Comment by taylor13** [comment]
I think what is requested here is the difference in the net SW flux at the base and top of each ocean layer.  "absorbtion" in the standard_name makes it clear that we are not talking about the opposite (energy loss from the layer).  The absorbed energy is independent of what the convention is governing the SW flux itself, so I agree with @jkettleb that "positive" should be dropped for this variable.

**Comment by jkettleb** [comment]
Hello Karl @taylor13,

Thanks for finding time to have a quick look at this.  I was a little worried in case we had misunderstood this diagnostic.  But I think our interpretation is consistent with yours.

Jamie

**Comment by martinjuckes** [comment]
This is not consistent with usage elsewhere. The use of `positive` has nothing to do with ambiguity being present of absent in the standard name (e.g. rsds), it is there because the physical quantity being represented could have one of two sign conventions. I'll change if necessary, but I'd like an explanation which is consistent with usage elsewhere.

**Comment by taylor13** [comment]
rsds is a vertical flux (formally a "flux density") across a single "quasi-horizontal" surface with a positive direction defined as either "up" or "down", whereas rsdoabsorb is a rate of energy flow into a layer (not across a single horizontal surface).

Perhaps some background would be helpful.  Although vertical fluxes of energy, substance, and momentum are traditionally saved by modelers, not all of them adopt the same sign convention.   The CF standard names recognize this and provide options, for example, for both net_downward_shortwave_flux_in_air and net_upward_shortwave_flux_in_air, which makes the positive direction explicit.  In CMIP where we want to facilitate  conformance with the specs using CMOR, we provide users with an option to say what their convention is for the positive direction of a flux, and then CMOR looks at the specs and reverses the sign of their data before writing it, relying on the "positive" entry in the table.  Thus, all energy fluxes and surface stress invariably are assigned a "positive" value ("up" or "down").  Sometimes the "positive" entry is the only way to deduce the direction of a vertical flux (i.e., when it isn't indicated by the standard_name as in, for example, conductive_heat_flux_at_sea_ice_surface)

For certain vertical fluxes, all or nearly all groups have adopted the same convention for a vertical flux, and the direction is implied by the standard name, so the "positive" indication is not essential and has been omitted (e.g., "precipitation"  the flux is invariably considered positive downward)

Reviewing the tables, it appears that a "positive" attribute needs to be defined in the following cases (because direction isn't implied by the standard_name and/or groups may adopt different conventions in practice):
EhrPt:  rsucsaf, rsucsafbnd, rsucsbnd
Emon: fN2O, fNOx, expfe, irrLut, fahLut, fLulccAtmLut 
SImon: siflcondtop, siflcondbot

And the following should *not* have "positive" defined:
Amon & CFsubhr: fco2antt, fco2fos
E3hr: gpp??
Emon: fHarvestToProduct, rsdoabsorb

**Comment by matthew-mizielinski** [comment]
Should we also drop the positive from `evs` ("Water Evaporation Flux Where Ice Free Ocean over Sea") in `Omon`? I think  it only makes sense if positive='up' in this case.

**Comment by taylor13** [comment]
That would be o.k. with me.

**Comment by martinjuckes** [comment]
For 01.00.21 I'll make these changes:
"positive" attribute dropped: gpp*, fco2antt, fco2fos, evs*, fHarvestToProduct, rsdoabsorb
"positive" attribute added: "up": rsucsaf, rsucsafbnd, rsucsbnd, fN2O, fNOx, fLulccAtmLut, fahLut; "down": siflcondtop, siflcondbot, expfe;

For "irrLut" (Irrigation flux including any irrigation for crops, trees, pasture, or urban lawns) I'm not sure what you would want for the "positive" attribute. I assume an irrigation flux will be from the irrigation system onto the land, but I'd imagine it could be pumped from below or gravity fed from above.

**Comment by taylor13** [comment]
irrLut increases the wetness starting at/near the surface and then diffusing down.  Other water fluxes that wet the surface of the earth (usually from the atmosphere) are postive down, so I suggest positive down for irrLutt.

**Comment by martinjuckes** [comment]
OK .. but I don't think it makes much sense.
