### ISSUE TITLE
CMORvar 'prra' and 'prrc' in table 'E3hr' should have cell method 'mean where land'

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#269]
because they are requested there by LS3MIP (and show with that cell method for table Eday , also as a request by MS3MIP)

**Comment by martinjuckes** [comment]
There are two options here: they could go for consistency with the core 3 hourly variables (`tas`, `rsus` etc) which are requested over the whole grid cell, or have it masked, as for the daily data. At the moment they are not asking for a masked 3 hourly version of `tas` (possibly because it would increase the volume too much if they requested their own versions of all the core 3 hourly variables), and I imagine it will be good to have `tas` and `prra` consistent.  I'll check.

**Comment by jkettleb** [comment]
We're a little confused by the LS3MIP data request.  Many of the quantities they request as 'area: mean where land' are (at least in our coupled models) not output with a land/sea distinction: coastal points are just grid box means.  Should we submit these for any coupled model runs (or are they only really needed for land only model runs)?  If they are requested for coupled models should we just submit the grid box mean?

**Comment by martinjuckes** [comment]
Hello @jkettleb : yes, I think that is correct. If your model does not distinguish between land and sea within the grid box, then the `where land` and `where sea` area means must both equal the mean for the whole grid cell.
