### ISSUE TITLE
standard_name = "missing" is non-compliant with CF and breaks CMOR

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#279]
There are a number of instances where standard_name in the data request has the value "missing" (see, for example, table Efx).  This will break the ESGF publisher and CMOR and renders files non-compliant with CF.  

The problem can be fixed by replacing all instances of "missing" with "" (an empty string).

**Comment by taylor13** [comment]
Related issue:  there is at least one case (wtem) where standard_name is set to "unset".  Like "missing", "unset" will break things.

**Comment by senesis** [comment]
I can quote a few other cases : ['H2wv', 'O18wv', 'H2p', 'H2s', 'O18p', 'O18s', 'O17wv', 'od550so4so', 'O17p', 'O17s']

**Comment by matthew-mizielinski** [comment]
The full set of variables with these invalid standard names, according to dreq version 01.00.20;
```
from dreqPy import dreq
dq = dreq.loadDreq()

# the sn dictionary attached to the MIP variable section of the inquiries
# module for the data request relates the standard_name to a list of uids 
# identifying the MIP variables.
uids = dq.inx.var.sn['missing'] + dq.inx.var.sn['unset'] 
for uid in uids:
    print dq.inx.uid[uid]

Item <1.2 MIP Variable>: [sandfrac] Sand Fraction
Item <1.2 MIP Variable>: [O18s] 18O in solid precipitation
Item <1.2 MIP Variable>: [H2wv] H2 in water vapor
Item <1.2 MIP Variable>: [ugrido] UGRID Grid Specification
Item <1.2 MIP Variable>: [O17p] 17O in total precipitation
Item <1.2 MIP Variable>: [sweLut] snow water equivalent on land use tile
Item <1.2 MIP Variable>: [od550so4so] Stratospheric Optical depth at 550 nm (sulphate only) 2D-field (here we limit the computation of OD to the stratosphere only)
Item <1.2 MIP Variable>: [slthick] Thickness of Soil Layers
Item <1.2 MIP Variable>: [laiLut] Leaf Area Index on Land Use Tile
Item <1.2 MIP Variable>: [hfdsnb] Downward heat flux at snow base
Item <1.2 MIP Variable>: [cTotFireLut] Total carbon loss from natural and managed fire on land use tile, including deforestation fires
Item <1.2 MIP Variable>: [siltfrac] Silt Fraction
Item <1.2 MIP Variable>: [O18wv] O18 in water vapor
Item <1.2 MIP Variable>: [O18p] 18O in total precipitation
Item <1.2 MIP Variable>: [H2p] 2H in total precipitation
Item <1.2 MIP Variable>: [H2s] 2H in solid precipitation
Item <1.2 MIP Variable>: [rootdsl] Root Distribution
Item <1.2 MIP Variable>: [O17s] 17O in solid precipitation
Item <1.2 MIP Variable>: [nwdFracLut] fraction of land use tile tile that is non-woody vegetation ( e.g. herbaceous crops)
Item <1.2 MIP Variable>: [ksat] Saturated Hydraulic Conductivity
Item <1.2 MIP Variable>: [fldcapacity] Field Capacity
Item <1.2 MIP Variable>: [O18sw] O18 in sea water
Item <1.2 MIP Variable>: [O17wv] O17 in water vapor
Item <1.2 MIP Variable>: [wilt] Wilting Point
Item <1.2 MIP Variable>: [wtem] Transformed Eulerian Mean upward wind
```

**Comment by taylor13** [comment]
variables with invalid standard names cannot be published.  In particular "missing" and "unset" are not valid standard names.

**Comment by senesis** [comment]
Should then quote applicable version of CF standard_names table

**Comment by taylor13** [comment]
elsewhere I have seen a report that another non-standard name is:  sea_ice_time_fraction.

**Comment by senesis** [comment]
One should be careful when using the sn attribute of MIPvars in DR  :

```
def sn_type_of(varlabel) :
    uid=dq.inx.var.label[varlabel][0]
    firstvar=dq.inx.uid[uid]
    var_sn=dq.inx.uid[firstvar.sn]
    return var_sn._h.label
print "wilt-> " , sn_type_of('wilt')
print "tas-> " , sn_type_of('tas')
print "sitimefrac ->",sn_type_of("sitimefrac")

```
Gives
```
wilt->  remarks
tas->  standardname
sitimefrac -> remarks
```

**Comment by taylor13** [comment]
Since standard_name is an ESGF search facet, it is particularly important to make sure these are correct, complete, and consistent across all models.  

@matthew-mizielinski @martinjuckes @senesis : does anyone have a complete list of variables with standard_names that are currently 1) undefined, 2) not yet approved by CF, and/or 3) incorrect?  

A couple months ago @matthew-mizielinski provided a list above, but I think many of these have gotten corrected.    

The variable wtem found in EdayZ and EmonZ is set to "unset" which is not a valid standard_name.  Are there other remaining problems with standard_names?  I think we should try hard to work out *all* that the standard_name issues for the next release.

If somone has a way to check that all CMIP6 variables have approved standard_names, please share the list.

**Comment by senesis** [comment]
As of DR01.00.21, the DR 'vars' which attribute 'sn'  has status 'remarks' is as shown in next comment. It is very long. Because we will use that DR version, we will have to assume that ESGF users will use the CMIP6 variable name as a search facet, rather than the standard_name.

**Comment by senesis** [comment]
C4MIP ['cLitterCwd', 'cOther', 'cSoilAbove1m', 'cSoilBelow1m', 'cSoilLevels', 'cSoilPools', 'cStem', 'co23D', 'fAnthDisturb', 'fBNF', 'fCLandToOcean', 'fDeforestToProduct', 'fFireAll', 'fFireNat', 'fHarvestToProduct', 'fLitterFire', 'fNAnthDisturb', 'fNLandToOcean', 'fNLitterSoil', 'fNOx', 'fNProduct', 'fNVegLitter', 'fNVegSoil', 'fNdep', 'fNfert', 'fNgasFire', 'fNgasNonFire', 'fNloss', 'fProductDecomp', 'fVegFire', 'fVegLitterMortality', 'fVegLitterSenescence', 'fVegSoilMortality', 'fVegSoilSenescence', 'nLeaf', 'nLitterCwd', 'nLitterSubSurf', 'nLitterSurf', 'nMineral', 'nMineralNH4', 'nMineralNO3', 'nOther', 'nRoot', 'nStem', 'nppOther', 'nppStem', 'raLeaf', 'raOther', 'raRoot', 'raStem', 'rhLitter', 'rhSoil', 'tSoilPools', 'wetlandCH4cons', 'wetlandCH4prod']

ISMIP6 ['lim', 'limnsw', 'litempbotfl', 'litempbotgr', 'strbasemag', 'tendacabf']

VolMIP ['aod550volso4', 'lwsffluxaero', 'lwtoafluxaerocs', 'swsffluxaero', 'swtoafluxaerocs', 'zmlwaero', 'zmswaero']

RFMIP ['aerasymbnd', 'albdiffbnd', 'albdirbnd', 'rsdcsaf', 'rsdcsafbnd', 'rsdcsbnd', 'rsdscsaf', 'rsdscsafbnd', 'rsucsaf', 'rsucsafbnd', 'rsucsbnd', 'rsuscsaf', 'rsuscsafbnd', 'rsutcsafbnd', 'solbnd']

LUMIP ['cProductLut', 'cTotFireLut', 'fLulccAtmLut', 'fLulccProductLut', 'fProductDecompLut', 'irrLut', 'laiLut', 'nwdFracLut', 'sweLut']

PMIP ['H2p', 'H2s', 'H2wv', 'O17p', 'O17s', 'O17wv', 'O18p', 'O18s', 'O18sw', 'O18wv', 'c13Land', 'c13Litter', 'c13Soil', 'c13Veg', 'c14Land', 'c14Litter', 'c14Soil', 'c14Veg', 'cLand', 'depdust', 'dissi14c', 'fN2O', 'fNgas', 'fNleach', 'fNnetmin', 'fNup', 'gppc13', 'gppc14', 'hcont300', 'intuadse', 'intuaw', 'intvadse', 'intvaw', 'lwsrfasdust', 'lwsrfcsdust', 'lwtoacsdust', 'mrlso', 'mrsfl', 'mrsll', 'mrtws', 'nLand', 'nLitter', 'nProduct', 'nSoil', 'nVeg', 'netAtmosLandC13Flux', 'netAtmosLandC14Flux', 'od550aerso', 'od550so4so', 'rac13', 'rac14', 'rhc13', 'rhc14', 'sedustCI', 'swsrfasdust', 'swsrfcsdust', 'wetlandCH4', 'wetlandFrac']

OMIP ['hfbasinpmadv', 'hfbasinpmdiff', 'hfbasinpsmadv', 'msftmrhompa', 'msftmzmpa', 'msftmzsmpa', 'msftyrhompa', 'msftyzmpa', 'msftyzsmpa', 'ocontempdiff', 'ocontemppmdiff', 'ocontemppsmadvect', 'opottempdiff', 'opottemppmdiff', 'opottemppsmadvect', 'osaltdiff', 'osaltpmdiff', 'osaltpsmadvect', 'sossq', 'tomint']

DAMIP ['jo2', 'jo3', 'oxloss', 'oxprod', 'vmrox']

AerChemMIP ['bs550aer', 'lossn2o', 'pod0']

CCMI ['flashrate', 'od550no3', 'od550so4', 'wtem']

CFMIP ['ccldncl', 'clcalipsoliq', 'clivic', 'reffcclwtop', 'reffsclwtop', 'scldncl', 'tnhuspbl', 'tnhusscp', 'tntd', 'tntpbl', 'tntscp']

CMIP6 ['ugrido']

LS3MIP ['albc', 'albsn', 'dcw', 'dfr', 'dgw', 'dmlt', 'drivw', 'dslw', 'dsn', 'dsw', 'dtes', 'dtesn', 'ec', 'eow', 'es', 'esn', 'et', 'fldcapacity', 'hfdsnb', 'hfrs', 'hfsbl', 'ksat', 'nudgincsm', 'nudgincswe', 'prrsn', 'prsnsn', 'qgwr', 'rivi', 'rivo', 'rootdsl', 'rzwc', 'sandfrac', 'sblnosn', 'siltfrac', 'slthick', 'snmsl', 'snwc', 'sw', 'tau', 'wilt', 'wtd']

SIMIP ['siareaacrossline', 'sidmassdyn', 'sidmassgrowthwat', 'sidmasslat', 'sidmassth', 'sidragbot', 'siflcondbot', 'siflcondtop', 'siflfwbot', 'siflfwdrain', 'siflswdbot', 'siforcecoriolx', 'siforcecorioly', 'siforceintstrx', 'siforceintstry', 'siforcetiltx', 'siforcetilty', 'siitdconc', 'siitdsnconc', 'siitdsnthick', 'siitdthick', 'simpmass', 'simprefrozen', 'sirdgconc', 'sirdgthick', 'sisaltmass', 'sishevel', 'sistremax', 'sistresave', 'sitempbot', 'sitimefrac', 'sndmassdyn', 'sndmasssi', 'sndmasssubl', 'sndmasswindrif', 'snmassacrossline']
List of 'MIP variables' in DR 01.00.21 which attribute 'sn' has value 'remark'  (rather than 'standardname')

FAFMIP ['pabigthetao', 'pathetao', 'prbigthetao', 'prthetao']

DynVar ['psitem', 'tauupbl', 'tauvpbl', 'tntnogw', 'tntogw', 'utendvtem', 'utendwtem', 'vtendnogw', 'vtendogw']

**Comment by senesis** [comment]
The number of entries above (sn with type 'remark') is 
  - 284 for DR01.00.21
  - 254 for DR01.00.22

**Comment by matthew-mizielinski** [comment]
I get a similar answer to @senesis; 278 out of 2026 CMOR variables at dreq v01.00.22 with standard names that are not in v49 of the CF list.  I've thrown my crude workings into a notebook [here](https://gist.github.com/matthew-mizielinski/e92bbf1a7fe74a2e56ddd28bf6aebe68) in case anyone wants to repeat this (or spot faults).

**Comment by matthew-mizielinski** [comment]
For the record; comparing v01.00.23 of the data request to v50 of the CF list leaves 222 CMOR variables without CF standard names.

**Comment by martinjuckes** [comment]
In 01.00.27 there is one variable with an invalid standard name.

**Comment by senesis** [comment]
[wrong_standard_names_in_DR21.txt](https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/files/2306562/wrong_standard_names_in_DR21.txt)
@taylor13  : The freeze date described in [WIP meeting notes](https://docs.google.com/document/d/1Ut_nxpd7D63hrHS9m3p_l3VAvlBtVQDUr0UyJGQid_I/edit)  had yet not been fixed (at least as far as I know). Hence, data producers had to begin publishing data using DR versions before 01.00.27. For CNRM and IPSL, that means 186 non-CF 'standard names' from DR01.00.21 (see attachment)

This means that this assertion from the meeting notes :

> For the small number of names in this category, a user will either need to use the variable *name* (not the standard name) in searching ESGF or search for both the uncorrected and corrected version of the standard name. 

does not represent a really tractable way for the users to search for the data. Is it really untractable for the ESGF search interface to cope with synonyms in standard_names ?

**Comment by martinjuckes** [comment]
@senesis : I think the answer to your last question is that this is not in the ESGF plans and so is not likely to happen. It may be possible to get it in a dwon-stream service such as climate4impact.
