### ISSUE TITLE
A question related to the description of the MIP Variable

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#290]
Hi Martin,

I was wondering whether it would be worth using the description provided by the Standard Name as the description of the MIP Variable in the cases where the description of the MIP Variable is empty. See, e.g. [ares](http://clipc-services.ceda.ac.uk/dreq/u/59176628-9e49-11e5-803c-0d0b866b59f3.html). The benefit of this is that the description is written (via CMOR) to the output netCDF files as a `comment`.

**Comment by taylor13** [comment]
See also https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/179

**Comment by martinjuckes** [comment]
Good idea .. I'll implement this for 01.00.22

**Comment by taylor13** [comment]
@ehogan @martinjuckes Some of the descriptions are now quite verbose ... more than 2000 characters for some variables.  This breaks CMOR, which currently has a limit of 1024 characters for its "comment" attribute (and all other string attributes).  In the next release of CMOR, we can enable it to handle longer comments, but be aware that CMOR places some constraints on the DREQ and we should check whether future releases of the DREQ will break CMOR before the release is official. 
I am also a little uncomfortable cluttering up the ncdump listing of global attributes with very long "comments" of nominal value (since they can be obtained online from the conventions website).  
I would vote to remove or substantially shorten them.

**Comment by taylor13** [comment]
@martinjuckes it would still be good to shorten many of the comments.  Doing so won't break anything.

**Comment by martinjuckes** [comment]
Cleaner descriptions for intppcalc, intppdiaz, intpppico, aerasymbnd, aerssabnd, diftrbbo, diftrebo, fNgas, fngasFire, fNgasNonFire, FNnetmin, fNup, fProductDecomp, fProductDecompLut, mmrsoa, mmrss, wetss, wetso4, wetoa, wetso2, hfss, hfssLut. 
22 done, 72 to go.

**Comment by ehogan** [comment]
@martinjuckes, would it be possible to get an update on this ticket?

**Comment by martinjuckes** [comment]
Hello @ehogan : the maximum description length is now 824. There are still a number of terms with description imported from CF standard names which are not ideal, but these will not be fixed in the near future (they are technically correct, and don't break anything). I'll close this issue.
