### ISSUE TITLE
cSoilAbove1m, cSoilBelow1m

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#293]
See https://github.com/PCMDI/cmor/issues/294

**Comment by taylor13** [comment]
An additional issue: I noticed that tsl and mrsol in the 6hrPlevPt table are variables that should be reported at all soil layers.  They incorrectly are functions of sdepth1 (which is the coordinate for the uppermost 10 cm), and should instead be functions of sdepth.

**Comment by taylor13** [comment]
Given that we already defined sdepth1 as a layer extending to 10 cm below the surface, perhaps we should define sdepth10 as a layer extending to 1 m (10 decimeter) below the surface.  The coordinate value should be at the mid-point (i.e, 0.5 m) and the bounds at 0 m and 1 m.
Since we are apparently requesting the carbon content in the surface layer, I think it would be *much* better to request that the total carbon content be also reported (rather than the content below 1 m).  Anyone could easily calculate the carbon content below 1 m by subtraction (total - surface layer).  Then we would define the total carbon content without using a coordinate.  The standard name ("soil_carbon_content") would indicate this includes the total soil column.

**Comment by ehogan** [comment]
@taylor13 I already asked Martin about `tsl` for `6hrPlevPt`, see #289 :)

**Comment by taylor13** [comment]
Oh, good.  Perhaps mrsol was also corrected too.  This still leaves the issue raised at PCMDI/cmor#294 concerning carbon in the upper 1 m and below 1 m.

**Comment by martinjuckes** [comment]
Concerning the HighresMIP request: they have explicitly stated that they only want data for the surface layer .. because this data is high frequency (6 hourly) they do not want to request data from soil layers which are not relevant to their planned analysis. 

I'll check with Chris Jones about cSoilBelow1m.

**Comment by taylor13** [comment]
Please note that whatever you choose for the dimension entry in the data request (sdepth1m??), the "altLabel" (i.e., "outname") that will be the coordinate dimension name appearing in the netCDF file should be "depth".

**Comment by taylor13** [comment]
Looks like this can be closed?  right?

**Comment by martinjuckes** [comment]
Yes, soilBelow1m has been removed from the request.
