### ISSUE TITLE
A number of variables (or structures) lost their cell_measures in DR01.00.22

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#313]
This is the case at least for these variables in that tables. :
  - 3hr : huss, mrsos, tas, uas, vas
  - 6hrPlev : uas,vas,rv850,zg500
  - Amon : hurs,huss,sfcWind,tas,uas,vas 
  - CFday and CFmon:  cl?calipso
  - CFday : wap500
  - Emon : sfcWindMax
  - Lmon: mrsos
  - day: same as for 3hr + sfcWind and sfcWindmax
All have a single-valued dimension. But other single valued structures such as str-082, str-083, str-130, str-189 did not loose their cell measure value

**Comment by taylor13** [comment]
I was about to report this, but I see @senesis beat me to it.  Is it understood why this happened?

Since uas, vas, rv850, sfcWind, and sfcWindmax are not always carried at the center of grid cells, areacell *should* be dropped for these.  

But areacell is definitely needed for huss, mrsos, tas, zg500, hurs, wap500.

**Comment by martinjuckes** [comment]
Sorry .. this was an error introduced as a side effect of some changes made elsewhere.
