### ISSUE TITLE
positive attribute for deposition fluxes?

### ISSUE THREAD

**Issue by lwhorowitz** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#328]
What is the intended sign convention for the wet and dry deposition fields in the CMIP6 data request. For instance:

Variable: wetso2
title: wet deposition rate of so2
units: kg m-2 s-1
CF Standard Name: TendencyOfAtmosphereMassContentOfSulfurDioxideDueToWetDeposition

I would interpret the variable name and title as meaning that positive values
represent deposition (from the atmosphere to the surface). But, the CF standard
name seems to suggest the opposite.

A "positive" attribute would remove this ambiguity.

This issue applied to the following requested variables: drynh3, wetso2, wetnoy , fNdep, dryoa, dryso4, wetnh4, depdust, drynh4, wetnh3, drydust, dryso2, wetdust

**Comment by martinjuckes** [comment]
Good question. I think we should go with the sign implied by the title, but will check by email to see what others think. 

"depdust" is OK as it is, because the standard name is a "surface_downward_mass_flux".

There are some additional variables with the same problem: wetoa, dryo3, wetss, wetbc, dryss, drynoy, drybc.

I think we need new standard names, either `minus_one_times_tendency_.....` or `surface_downward_mass_flux-`

**Comment by martinjuckes** [comment]
New standard names have been added in 01.00.25 to remove the ambiguity,
