### ISSUE TITLE
cell methods corrections needed

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#361]
A correction was requested by @adcroft at https://github.com/PCMDI/cmip6-cmor-tables/pull/217, but the problem is in the data request, which is why I am copying it here:

```
Transport variables are extensive (integrated) in two dimensions and should not have "area: 
mean" in the cell methods. Examples of corrections include:

    hfbasin is the longitudinally and depth integrated transport of heat across a latitude, by basin. 
The "longitude" and "olevel: dimensions are reduced by the integration and the cell method 
should then contain "longitude: sum (basin) olevel: sum".
    msftmrho is the longitudinally and vertically integrated, then vertically summed, mass transport
 across a latitude and should have "longitude: sum (comment: basin sum[ along zig-zag grid 
path])" in the cell method. "rho: sum" is omitted since the double sum in the vertical renders "rho:
 point" and which is implied by omission (I think).
    vmo is the y-direction mass transport between cells in units of "kg s-1". It is extensive in the
 longitude and vertical directions and so should have "longitude: sum olevel: sum time: mean" in
 the cell method. Because this is a 3d (spatial) variable I think it appropriate to include "latitude:
 point" to explicitly indicate that the variable is not averaged or summed in the transport direction.
```

Further corrections were requested by @adcroft at     

```
Some of the primary physical variables were missing the volume cell method.

    e.g. thetao is intensive and is the average potential temperature in a cell and so should 
have "volume: mean" in the cell method.

Also

    thkcello is extensive in the vertical direction so should have "olevel: sum".
    volcello is simply extensive and should have "volume: sum" for the cell method.
```
Regarding thetao, I don't think  we can *require* that all intensive variables represent volume means.  Certainly,  u and v, which are usually carried at grid cell faces or corners, may not represent a grid-cell mean value, so it would be inappropriate to set "cell_methods = "volume: mean".  For CMIP6, where we don't currently specify a cell_methods for a dimension, I think we should continue to omit it; we can reevaluate for CMIP7.  Only when the cell_methods is wrong at this point should we make a change.

Regarding the last two variables mentioned above (thkcello and volcello), I think the intent of cell_methods is to characterize how samples within a cell get combined.  In the case of dimensions of cells (and products of those dimensions), the cell_methods should be omitted because they are by definition extensive (sub-samples couldn't be combined sensibly in any other way).  [Of course if the dimensions of a cell vary in time, it would be good to indicate for the time-dimension what the cell_methods is. ]

A similar argument could be made for "fractions" (e.g., land fraction, ocean fraction).  I don't think it is really necessary in this case to say the fractions of grid cells have cell_methods = "area: mean"; the fraction of a grid cell is unambiguous.

**Comment by adcroft** [comment]
(Thanks for creating this issue after I addressed the wrong repository.)

cell_methods are optional for intensive or extensive variables where the implied cell_methods can be assumed to be either "volume: mean" or "volume: sum" (see [4th paragraph of 7.3](http://cfconventions.org/cf-conventions/cf-conventions.html#cell-methods) ).  In other words, all intensive variables are assumed to represent volume means. The problem I have with the current standard is the asymmetry between area and volume. I would be comfortable omitting both area and volume from intensive variables such as `thetao` but requiring only "area: mean" is hard to justify. It suggests that the vertical statistics might be different and if it is (or can be) then it should be specified (the vertical method could legitimately be either point or mean for an intensive variable). The convention recommends being explicit about methods for all dimensions (5th paragraph). My pull request was meant to bring uniformity to the standard. However, omitting the volume method is not breaking the rules so your preference to continue omitting volume works for some cases.

I agree that `u` and `v` might not be volume means and is model dependent. Therefore, requiring a specific set of cell methods is problematic. Nevertheless, models should provide them because the defaults for intensive variables fails here. Most structured finite volume models would need to provide "longitude: point latitude: mean olevel: mean", "longitude: mean latitude: point olevel: mean" respectively for u and v. Omitting the dimensional methods and assuming the intensive "volume: mean" is a case where the assumed method would be wrong (for many models). So the standard should not specify the methods but the dimensional methods should be provided.

The variables `thkcello` and `volvello` are not merely dimensions of cells. In a non-Boussinesq model `volcello` could be a thermodynamic variable, and `thkcello` is the primary dynamic variable in a general coordinate Boussinesq model. In the case of `thkcello`, because it is extensive in one dimension and intensive in two, it does not fall in a default category and the cell_methods should therefore be explicit: "area: mean olevel: sum".

`volcello` does fall into the extensive default category, in which case I suggest providing either both ("area: sum volume: sum"), or neither (""). Currently, the "area: mean" is wrong.

Yes, land fraction is intensive and so defaults to "area: mean".

**Comment by taylor13** [comment]
nb. in CMIP5 the cell_methods for volcello, areacello, sftlof, areacella, sftlf, and sftgif were all unspecified (=""), and none of these variables varied in time.  We probably should do the same for CMIP6. 

For most variables in CMIP6 that represent a value for an "entire" grid cell, I think it would be best avoid specifying exactly how it is representative (e.g., a mean vs. a "point") because this may be model dependent.  CMOR3 in particular cannot handle options for this attribute, so leaving it unspecified ("vague") is better than specifying it (since the specification will only be correct for some models).

Not sure I understood thkcello and volcello problem in non-Boussinesq models.  The cell thickness is *not* a continuous function of depth, longitude or latitude; it has no sub-grid variation in these dimensions and it is defined discreetly for each grid cell, so it doesn't need a cell_methods specification for depth, longitude or latitude.  If it is a function of time, then for this dimension the cell_methods should be specified ("mean" is the correct choice).

**Comment by adcroft** [comment]
> CMIP5 the cell_methods for volcello, areacello, sftlof, areacella, sftlf, and sftgif were all unspecified (="")

Although I prefer not to use CMIP5 as a example of what to do moving forward, using the default methods ("") for all the above would work. Note that `thkcello` is not in that list.

> For most variables in CMIP6 that represent a value for an "entire" grid cell, I think it would be best avoid specifying exactly how it is representative (e.g., a mean vs. a "point")

I thought the point was to define the variables to allow comparison across models? Allowing models to define variables as they see fit helps me with the submission but it could get in the way of inter-model comparison. This would require changing all the intensive cell methods in the request from "area: mean" to "--MODEL"? (This is not my preferred route)

> cell thickness is not a continuous function of depth, longitude or latitude; it has no sub-grid variation in these dimensions

The data we are submitting is constructed by summing over finer vertical levels and so the final cell thickness is truly the sum over sub-divisions in olevel. However, my point is that cell_methods is not just a definition of the statistics for the cell but also a rule by which to further process the variable. There are several ways to "try" to calculate a global ocean volume from `thkcello` but the correct way is specified by the cell method "area: mean olevel: sum".

**Comment by durack1** [comment]
This is linked to PCMDI/cmip6-cmor-tables#216 and PCMDI/cmip6-cmor-tables#217 - and these can be closed when a resolution is completed for this issue

**Comment by martinjuckes** [comment]
@adcroft -- thanks for raising these.

(1) `longitude: mean (basin)` replaced with `longitude: sum (basin) depth: sum`; (`depth` rather than `olevel` because we refer to the vertical coordinate via the standard name ... `olevel` is only a CMOR label);

(2) htovgyre, htovovrt, sltovgyre, sltovovrt set to above cell methods;

(3) msftmrho etc: changed to `longitude: sum (comment: ...) depth: sum`;

(4) umo, vmo: These have the cell measures directive "--OPT", meaning that people may choose to provide them on the cell vertices. For this reason, the spatial parts of the cell_methods string are not specified. I believe the interpretation in this case is that additional spatial cell_methods may be added by the data provider to define how they have complied with the request.

I hope this captures the main issues. There are some compromises which we may wish to re-consider in the future ... so I've put a marker for CMIP7 discussions here: https://github.com/cmip6dr/cmip7_forward_look/issues/27
