### ISSUE TITLE
wrong outnames for sw18O and sw17O

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#379]
@martinjuckes (cc @mauzey1) :  We have found these inconsistencies in the data request (29):

Under 1.3 CMOR variable : [sw18O] Isotopic Ratio of Oxygen-17 in Sea Water
the vid is sw18O but the label is sw17O.  Should sw180 be changed to sw17O?  

Under 1.3 CMOR Variable: [prw18O] Isotopic Ratio of Oxygen-18 in Sea Water
the vid is prw18O and the label is prw18O.  Should "prw" be changed to "sw"

There seem to be other inconsistencies between prw17O and prw18O. (check standard names and descriptions/comments)

Please check that within the data request, the cmor variables are consistent with the MIP variable definitions.  In particular the MIP variable sw17O can't be found in  the CMOR variable list.

**Comment by martinjuckes** [comment]
Sorry about this .. corrected for the next update.  CMOR and MIP variables have now been checked and match apart from the following exceptions:
1. Where there are two options for a CMOR variable, and one option has something appended to the name (following the approach used in CMIP5):

- Clim: for climatologies (7 instances);
- 2d: for surface version (as opposed to depth dependent fields - 15 instances);
- 27: for version on 27 pressure levels (29 instances);
- 4: on 4 pressure levels (rather than 3: 2 instances);
- 7h: on the plev7h pressure levels: 11 instances);
2. CMOR variables `latitude` and `longitude` have MIP variable names `lat`, `lon`. This behaviour is inherited from CMIP5, so presumably will not break anything.

I've corrected titles and descriptions of `prw17O` and `prw18O` to bring them into line with the standard names.

One other variable name needed adjusting: ugrid --> ugrido in the CMOR variable record.

**Comment by taylor13** [comment]
@martinjuckes We might want to get these corrections in as soon as we can.  Have you scheduled the next release?

**Comment by martinjuckes** [comment]
I'm aiming to get the next beta release out today.

**Comment by taylor13** [comment]
fantastic!

**Comment by taylor13** [comment]
I think this probably can be closed.
