### ISSUE TITLE
standard_names possibly missing?

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#381]
@martinjuckes .  @jhardenberg has raised an issue (https://github.com/PCMDI/cmip6-cmor-tables/issues/232) concerning a missing standard_name in the CMOR table.  In our table the coordinate variable "typeresidual" doesn't have a standard name.  Should it and should it be area_type?

I also noticed that the coordinate variable "vegtype" also doesn't have a standard name.

If your data request has defined standard_names for these variables, then I suppose we have a problem in how we generate the CMOR table of coordinates.

**Comment by martinjuckes** [comment]
Both "vegtype" and "typeresidual" are problematic because they do not use valid CF Area Types (https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/blob/master/cmip5_landCoverUsage.xls lists the 44 non-compliant area types used for `vegtype` in CMIP5). We could give it them standard name `area_type`, but then the data value for the coordinate variable would not be valid. This just shifts the error.

This was discussed in April 2017/18 and we decided to postpone further discussion: (#296) and https://github.com/cmip6dr/cmip7_forward_look/issues/2

**Comment by taylor13** [comment]
O.K.  Thanks for reminding me.  I'll close this.
