### ISSUE TITLE
cell_measures for ua and va for 6hrLev has the value @OPT

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#40]
Following the link provided by the "2.3 Dimensions and related information" attribute for [ua](http://clipc-services.ceda.ac.uk/dreq/u/babb47a6-e5dd-11e5-8482-ac72891c3257.html) for `6hrLev` shows that the `cell_measures` is incorrectly set to [@OPT](http://clipc-services.ceda.ac.uk/dreq/u/f94870ca-80ba-11e6-ab6e-5404a60d96b5.html). This also affects `va` for `6hrLev`.

**Comment by matthew-mizielinski** [comment]
As I understand it from Martin, @OPT means that you have the option of producing these variables on their "native" grids, i.e. the U or V points, or on the T points. Note that the cell_measures should be left empty if the U or V points are used, or something like `area: areacella` if the T points are used.

**Comment by martinjuckes** [comment]
Matthew is correct -- except that it should "--OPT" in the file. The presence of "@OPT" is a bug which I'll fix in 01.beta.40. There is a definition here: http://clipc-services.ceda.ac.uk/dreq/u/ATTRIBUTE::structure.cell_measures.html . See also https://www.earthsystemcog.org/projects/wip/drq_interp_cell_center . This notation was introduced in order to clarify the distinction between such variables and the majority, which should be interpolated to cell centres, and a small number which should be provided as they are used in the model (indicated by

**Comment by ehogan** [comment]
Thank you for the information and links, @martinjuckes :)

**Comment by jypeter** [comment]
@martinjuckes I have just noticed this _--OPT cell_measures_ in the DR and found this issue when trying to find out if this was a bug I should report or not.

Is this documented somewhere on the COG _CMIP6 Data Request_ section?
