### ISSUE TITLE
Possibly incorrect time sampling of ps in table E6hrZ

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#404]
There are 3 variables requested in table E6hrZ.  Two of them want time-mean values, but ps indicates it should be a point value.  I'm guessing this inconsistency was inadvertant.  Suggest ps be sampled in time as "point".  See https://github.com/PCMDI/cmor/issues/552

**Comment by martinjuckes** [comment]
Hi @taylor13 : yes, this is true. But this is also one of the `ps` variables which was only included to support CMOR (see https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/391) and which is no longer needed. It is not directly requested. Since it is now redundant, it might be easier to just remove it?

**Comment by martinjuckes** [comment]
Removed in 01.00.32

**Comment by taylor13** [comment]
Thanks, Martin.
