### ISSUE TITLE
Typos in data request

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#41]
I've found the following variables with some minor issues in their entries (present at 01.beta.39);

c4PftFrac :: title and description conflict over whether this is a fraction or a percentage.
cOther :: title contains "Vegetation Momponents"
rlucs :: description contains "rongwave radiation"
MIP variable clisccp & CMOR variable clisccp7c :: there is a conflict between the use of "percentage" and "fraction" in these variables.

tsl/emDay :: specified as being on atmosphere levels
(mrsfl, mrsll, mrsol)/emMon :: variables specified as single level rather than soil levels

**Comment by matthew-mizielinski** [comment]
I've just checked and most of the above are still present at 01.beta.41

**Comment by martinjuckes** [comment]
OK, I think these will be fixed in 01.beta.43. Also tsnl (temperature profile in snow). 

The fraction/percentage issue goes back to CMIP5: in CMIP5 a large number of variables described as fractions were requested with units "%". In a small but significant number of cases such variables were archived as fractions rather than percentages, so I've been trying to change the names and descriptions to be more consistent with the units (in the CF convention, however, terms such as `area_fraction` are intended to be used with either fractions or percentages, to the standard names will not change).

**Comment by martinjuckes** [comment]
Fixed
