### ISSUE TITLE
Reducing the number of "day" variables requested by "CMIP" for the full historical period

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#62]
The number of variables requested for the complete run can be reduced (email from Karl) .. pending confirmation.

**Comment by taylor13** [comment]
Just confirming what I wrote in my email:

I've just looked again at the data request for the historical run (beta.45):

drq -m CMIP --xls -e historical

In the  cmvme_CMIP_historical_1_1.xlsx "day" table (attached) the first dozen variables show that they are needed only for years 1950-2014, and the rest are needed for all years of the historical run.  I think instead, we need the first 9 variables for all years and the rest only for years 1950-2014.

I think the same problem exists for all of the DECK simulations.

**Comment by taylor13** [comment]
@martinjuckes Did this change get included in the 1.00.01 release?  If not, I think we need to make the change now and release 1.00.02.  As I understand it some groups have already begun processing output from their DECK runs.  We want them to save the first 9 variables for *all* years, which they won't do if this change hasn't been implemented.  That's why it is essential to correct this problem with highest priority.

**Comment by martinjuckes** [comment]
Done
