### ISSUE TITLE
Cell Methods for sea-ice variables

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#93]
Some feedback from a review of the cell methods for the sea-ice variables in version 1.00.01 of the data request by Alex West (Met Office):

`sifl*` variables:  I think that these should all just be ‘time: mean’; as extensive variables which are naturally zero where there is no sea ice, they should not need to be masked by siconc.

`siitdconc`, `siitdsnconc`: again I think these should just be ‘time:mean’ as they’re naturally zero where there is no ice.

`siitdthick`, `siitdsnthick`: these are said to be masked by `siconc`, but in fact the definition calls for them to be reported as a fraction of ice area and snow area in that category respectively!  So I think the cell_methods should be 

`area: time: mean where sea_ice_cat (comment: mask=siitdconc)` and
`area: time: mean where snow_cat (comment: mask=siitdsnconc)`

respectively.

`simprefrozen`: this is requested as fraction of meltpond area, so should probably be something like `area: time: mean where sea_ice_pond (comment: mask=simpconc)`

`sirdgthick`: this is requested as fraction of ridged ice area, so should probably be something like: `area: time: mean where sea_ice_ridged (comment: mask=sirdgconc).`

One or two other issues appear to have been fixed at v1.00.02 (published yesterday?)

**Comment by martinjuckes** [comment]
sifl*: the `cell_methods` string is a modifier of the parameter defined by the `standard_name`. E.g. for `sifllwutop` the `standard_name` is `surface_upwelling_longwave_flux_in_air`, which is defined over the whole grid. In your model, I suppose, the variables are defined in such a way that they only exist over sea-ice and no further masking is required -- because the masking is implicit in the formulation of the model.

siitdconc, siitdsnconc: The 2nd of these has a proposed standard name snow_area_fraction_over_categories .. which could be non-zero over land and land ice (including floating ice shelves), so the masking is necessary. It makes sense to use the same masking for the first. 

siitdthick, siitdsnthick: `where sea_ice_cat` is not allowed, as `sea_ice_cat` is not a valid CF area type, but I think you are right that there is a problem: we should probably use `area: time: mean where sea_ice (comment: mask=siitdconc)` for the first, meaning that the variable is undefined where the amount of sea ice, as defined by `siitdconc(cat,time,lat,lon)` is zero. The variable siitdsnthick is about snow thickness in ice thickness bands ... not clear from the variable definition, but that is what is intended. The same is true for ice thickness in a band ... it is undefined where the band does not exist.

**Comment by martinjuckes** [comment]
Done
